Repository opensource-workshop/connect-cms, pull requests merged in 2022-08, with the labels that each got.

#1395 [フォトアルバム]画像拡大表示の不具合修正（スマホでの画面はみだし、画像のマウスカーソル）
  resources/views/plugins/user/photoalbums/default/index.blade.php
Labels: bug, plugin(Photoalnum)

#1392 [データベース]tableテンプレートでのスマホ時の表横スクロールとタイトル行の改行禁止
  resources/views/plugins/user/databases/table/databases.blade.php
Labels: enhancement, plugin(database)

#1398 bugfix: コア, フレームデザインでprimaryの時、フレームタイトルが空だと歯車ボタンが見ずらい不具合修正
  resources/views/core/cms_frame_header.blade.php
Labels: bug

#1400 ページ管理, ページ権限一覧追加
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/page_manage_tab.blade.php
  resources/views/plugins/manage/page/role_list.blade.php
Labels: new feature

#1403 カレンダー, 登録時は終了日に今日日付もセットする
  app/Plugins/User/Calendars/CalendarsPlugin.php
Labels: enhancement

#1406 [アップロードファイル]ユーザーディレクトリ機能、JSファイルの読み込みもできるように追加しました
  app/Http/Controllers/Core/UploadController.php
Labels: enhancement

#1408 [アップロードファイル]ユーザーディレクトリ機能、xmlファイルの読み込みもできるように追加しました
  app/Http/Controllers/Core/UploadController.php
Labels: enhancement
