Repository opensource-workshop/connect-cms, pull requests merged in 2022-12, with the labels that each got.

#1435 [マニュアル] 課題管理のマニュアルページへのリンク切れ修正（phpdocのみ修正）
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
Labels: bug, ignore for release

#1513 [コア] アップロードしたページがない場合、今まで500エラーで見えなかった。そのためページがない場合、ファイルは非表示とする
  app/Http/Controllers/Core/UploadController.php
Labels: bug

#1516 [nc3移行] カレンダーの予定の状態/施設予約の予約の状態・予定時間・連絡先・補足の移行ミス修正（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: bug, ignore for release

#1519 [カレンダー] 予定登録時にキャンセルボタンがきかないバグ修正
  resources/views/plugins/user/calendars/default/edit.blade.php
Labels: bug

#1518 [カレンダー] 登録後は初期画面へ画面遷移を見直し OW-1577
  app/Plugins/User/Calendars/CalendarsPlugin.php
Labels: enhancement

#1515 [施設管理] 施設の予約一覧の絞り込み追加 OW-590
  app/Plugins/Manage/ReservationManage/ReservationManage.php
  resources/views/plugins/manage/reservation/bookings.blade.php
Labels: enhancement

#1514 [固定記事] 表示コンテンツ選択のソートにアンカーを設定
  resources/views/plugins/user/contents/default/contents_list_buckets.blade.php
Labels: enhancement

#1520 [祝日管理] 独自設定の祝日と同じ日が計算の祝日にあれば、計算の祝日を消して、独自設定を有効にする。が実現できてなかったため修正
  app/Models/Common/YasumiHoliday.php
  app/Plugins/Manage/HolidayManage/HolidayManage.php
  app/Traits/ConnectCommonTrait.php
Labels: bug

#1521 [nc3移行] フォトアルバムの移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3PhotoAlbumDisplayAlbum.php
  app/Models/Migration/Nc3/Nc3PhotoAlbumFrameSetting.php
  app/Models/Migration/Nc3/Nc3PhotoAlbumPhoto.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement, ignore for release

#1522 [nc3移行エクスポート/移行インポート] 検索の移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc2/Nc2SearchBlock.php
  app/Models/Migration/Nc3/Nc3SearchFramePlugin.php
  app/Models/Migration/Nc3/Nc3SearchFrameSetting.php
  app/Models/User/Searchs/Searchs.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement, ignore for release

#1523 [nc3移行エクスポート] バグ修正-汎用DBのアップロードデータが無かった場合に対応, 施設予約で必須のブロックデータがない場合、施設予約は移行しない対応, [nc2/nc3移行エクスポート] ウィジウィグのタブコード混入を除去対応（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: bug, ignore for release

#1525 [nc2/nc3移行エクスポート] リンクチェックでmailtoはチェックしない [nc3移行エクスポート] 内部リンクチェックのダウンロードURLチェックミス修正, メニューの表示しないページ移行ミス修正（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: bug, ignore for release

#1526 [移行インポート] nc3プラグイン固有リンク（nc3ブログ・nc3汎用DB）をccプラグインリンクに置換（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement, ignore for release

#1527 [nc3移行エクスポート] createdがnullの場合"0000-00-00 00:00:00"が返ってきていたので対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, ignore for release

#1529 [nc3移行] 動画の移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3Video.php
  app/Models/Migration/Nc3/Nc3VideoFrameSetting.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement, ignore for release

#1530 [nc3移行エクスポート] 新着のtopic_frame_settingデータなしも移行する対応（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, ignore for release

#1531 [nc3移行] nc3プラグイン固有リンク（掲示板/キャビネット/FAQ/フォトアルバム/施設予約/カレンダー）をccプラグインリンクに置換（nc3-migrateブランチにマージ）
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement, ignore for release

#1532 [施設予約] 終日毎日繰り返し＋終了日指定だと＋１日予約される不具合修正
  app/Plugins/User/Reservations/ReservationsPlugin.php
Labels: bug

#1528 [コア] ダウンロード時にカウントする拡張子にmp3追加
  config/connect.php
Labels: enhancement

#1524 [コア] ログインのリンク名を.envで変更可能にする OW-1598
  .env.example
  config/connect.php
  resources/views/layouts/app.blade.php
Labels: enhancement

#1498 [nc3移行] 登録フォーム・FAQ・リンクリスト・カウンター・カレンダー・施設予約・フォトアルバム・検索・動画の移行対応 [nc2移行] 検索の移行対応 OW-1096
  app/Enums/FaqSequenceConditionType.php
  app/Models/Migration/Nc2/Nc2SearchBlock.php
  app/Models/Migration/Nc3/Nc3AccessCounterFrameSetting.php
  app/Models/Migration/Nc3/Nc3BlockSetting.php
  app/Models/Migration/Nc3/Nc3Calendar.php
  app/Models/Migration/Nc3/Nc3CalendarEvent.php
  app/Models/Migration/Nc3/Nc3Category.php
  app/Models/Migration/Nc3/Nc3FaqQuestion.php
  app/Models/Migration/Nc3/Nc3LinkFrameSetting.php
  app/Models/Migration/Nc3/Nc3PhotoAlbumDisplayAlbum.php
  app/Models/Migration/Nc3/Nc3PhotoAlbumFrameSetting.php
  app/Models/Migration/Nc3/Nc3PhotoAlbumPhoto.php
  app/Models/Migration/Nc3/Nc3RegistrationAnswerSummary.php
  app/Models/Migration/Nc3/Nc3RegistrationChoice.php
  app/Models/Migration/Nc3/Nc3RegistrationPage.php
  app/Models/Migration/Nc3/Nc3RegistrationQuestion.php
  app/Models/Migration/Nc3/Nc3ReservationEvent.php
  app/Models/Migration/Nc3/Nc3ReservationLocation.php
  app/Models/Migration/Nc3/Nc3ReservationLocationsApprovalUser.php
  app/Models/Migration/Nc3/Nc3ReservationLocationsReservable.php
  app/Models/Migration/Nc3/Nc3RoomRolePermission.php
  app/Models/Migration/Nc3/Nc3SearchFramePlugin.php
  app/Models/Migration/Nc3/Nc3SearchFrameSetting.php
  app/Models/Migration/Nc3/Nc3Video.php
  app/Models/Migration/Nc3/Nc3VideoFrameSetting.php
  app/Models/User/Faqs/Faqs.php
  app/Models/User/Faqs/FaqsPosts.php
  app/Models/User/Searchs/Searchs.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
  config/app.php
Labels: enhancement

#1535 マニュアルを1.3に対応させました。
  app/Plugins/Manage/PageManage/PageManage.php
  tests/Browser/Manage/IndexManageTest.php
  tests/Browser/Manage/PageManageTest.php
  tests/Browser/Manage/ReservationManageTest.php
  tests/Browser/Manage/page.csv
Labels: ignore for release

#1536 マニュアルにページ管理の説明を追加しました。
  tests/Browser/Manage/PageManageTest.php
Labels: ignore for release

#1538 サイト管理のマニュアル説明内容を追加しました。
  tests/Browser/Manage/SiteManageTest.php
Labels: ignore for release

#1539 グループ管理のマニュアルを更新しました。
  tests/Browser/Manage/GroupManageTest.php
  tests/Browser/Manage/GroupManageTest2.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release
