Repository opensource-workshop/connect-cms, pull requests merged in 2022-10, with the labels that each got.

#1445 [コア] ファイル形式チェックのエラーメッセージをわかりやすくしました
  resources/lang/ja/validation.php
Labels: enhancement

#1447 [課題管理] どの科目をクリックしても同じ科目が表示される不具合修正 OW-1419
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
Labels: bug

#1449 [コア] Connect-CMSのバージョンを出力するようにしました
  config/version.php
Labels: new feature

#1446 [掲示板投稿]返信あり状態での保存判定の修正をしました
  app/Models/User/Bbses/BbsPost.php
  app/Plugins/User/Bbses/BbsesPlugin.php
Labels: bug

#1450 [フォーム] 本登録後のメッセージをHTMLで記述できるようにする
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  resources/views/plugins/user/forms/default/forms_thanks.blade.php
Labels: enhancement

#1458 [スライドショー]画像の遅延読み込みに対応しました
  resources/views/plugins/user/slideshows/default/slideshows.blade.php
Labels: enhancement

#1462 [掲示板]投稿エラー不具合に対応しました
  app/Plugins/User/Bbses/BbsesPlugin.php
Labels: bug

#1460 [ユーザディレクトリ]テキストファイルを展開表示させる
  app/Http/Controllers/Core/UploadController.php
Labels: enhancement

#1463 [データベース] default・カードタイプ２列・design-table-dlテンプレートの詳細画面で公開終了・公開前のタグ表示が抜けていたので追加
  resources/views/plugins/user/databases/card_02/databases_detail.blade.php
  resources/views/plugins/user/databases/default/databases_detail.blade.php
  resources/views/plugins/user/databases/design-table-dl/databases_detail.blade.php
Labels: bug

#1464 [データベース] 編集者は自分以外の「公開終了」した記事、投稿日前の記事は表示しない
  app/Plugins/User/UserPluginBase.php
  resources/views/plugins/user/databases/card_02/databases.blade.php
  resources/views/plugins/user/databases/card_02/databases_detail.blade.php
  resources/views/plugins/user/databases/default/databases.blade.php
  resources/views/plugins/user/databases/default/databases_detail.blade.php
  resources/views/plugins/user/databases/design-table-dl/databases_detail.blade.php
Labels: enhancement

#1468 [ブログ] 一時保存で続きを表示する関連が登録されない不具合修正
  app/Plugins/User/Blogs/BlogsPlugin.php
Labels: bug

#1470 [Opac]OpacBookLents 配送希望フラグのデフォルト値を設定し、OpacAPIからの貸出に対応する
  database/migrations/2022_10_24_111729_change_delivery_request_opacs_books_lents.php
Labels: bug

#1467 [NC2移行]会員項目のNC2システム固定値と会員の作成日時を移行できるようにしました
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1465 [キャビネット]一覧のコンテンツ選択チェックボックスの全選択機能を追加しました。
  resources/views/plugins/user/cabinets/default/index.blade.php
Labels: enhancement

#1472 [コア] 本来のエラーログを出力するため、cc_configs未セットなら初期化するよう対応
  resources/views/layouts/app.blade.php
Labels: enhancement

#1478 [共通]多言語の辞書ファイルを修正しました。
  resources/lang/en/messages.php
  resources/lang/ja/messages.php
Labels: enhancement
