Repository opensource-workshop/connect-cms, pull requests merged in 2022-09, with the labels that each got.

#1409 [コア]Laravelをアップグレードしました（6.x -> 8.x）
  .gitignore
  app/Exceptions/Handler.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/ConnectLog.php
  app/Providers/AppServiceProvider.php
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
  config/queue.php
  config/session.php
  database/factories/UserFactory.php
  database/migrations/2022_08_31_185750_add_uuid_to_failed_jobs.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DefaultConfigsTableSeeder.php
  database/seeders/DefaultPagesTableSeeder.php
  database/seeders/DefaultPluginsTableSeeder.php
  database/seeders/DefaultReservationsTableSeeder.php
  database/seeders/DefaultUsersRolesTableSeeder.php
  database/seeders/DefaultUsersTableSeeder.php
  database/seeders/ElementaryschoolSeeder.php
  database/seeders/PTASeeder.php
  database/seeders/TruncateAllTables.php
  dev_2_option_private.ps1.example
  docker/app/Dockerfile
  option_private_2_dev.ps1.example
  public/index.php
  resources/lang/en/auth.php
  resources/lang/en/passwords.php
  resources/lang/en/validation.php
  resources/lang/ja/auth.php
  resources/lang/ja/validation.php
  resources/views/layouts/app.blade.php
  routes/web.php
  sync_dev_2_option_private.sh.example
  sync_option_private_2_dev.sh.example
Labels: developer update

#1411 bugfix: UploadedFile::getClientSize to getSize
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Forms/FormsPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Openingcalendars/OpeningcalendarsPlugin.php
  app/Plugins/User/Slideshows/SlideshowsPlugin.php
Labels: bug

#1415 Bugfix GitHub action dusk
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_daily.yml
Labels: bug

#1414 [掲示板]掲示板投稿でシステムエラーとなる事象を修正しました
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
Labels: bug

#1393 [コア]リリースノート自動生成で利用する設定ファイルを追加しました
  .github/release.yml
Labels: developer update

#1424 OW-1326 OPAC, 貸出リクエストのユーザIDが存在しないと貸出処理でシステムエラーになる不具合対応
  app/Plugins/User/Opacs/OpacsPlugin.php
Labels: bug

#1425 core, プラグイン内のシステムエラー表示をフレーム内に納める対応の不具合修正
  app/Plugins/User/UserPluginBase.php
  resources/views/core/cms_frame.blade.php
  resources/views/errors/error_inframe.blade.php
Labels: bug

#1427 [テーマ管理] テーマディレクトリに書込権限ない場合は、注意メッセージを表示
  app/Plugins/Manage/ThemeManage/ThemeManage.php
  resources/views/plugins/manage/theme/theme_generate.blade.php
Labels: enhancement

#1428 PULL_REQUEST_TEMPLATE.md のチェックリストにプルリクエストのルールのリンクを追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: developer update

#1426 [キャビネット]表示項目を追加しました（ダウンロード件数、更新者、作成者）
  app/Enums/CabinetFrameConfig.php
  app/Plugins/User/Cabinets/CabinetsPlugin.php
  resources/views/plugins/user/cabinets/default/frame.blade.php
  resources/views/plugins/user/cabinets/default/index.blade.php
Labels: enhancement

#1421 OW-1325 [OPAC] 郵送貸出リクエスト時の配送希望日時を追加
  app/Enums/DeliveryRequestFlag.php
  app/Enums/OpacConfigSelectType.php
  app/Models/User/Opacs/OpacsBooksLents.php
  app/Models/User/Opacs/OpacsConfigs.php
  app/Models/User/Opacs/OpacsConfigsSelect.php
  app/Plugins/User/Opacs/OpacsPlugin.php
  config/app.php
  database/migrations/2022_09_13_151048_create_opacs_configs_selects_table.php
  database/migrations/2022_09_14_120312_add_delivery_request_from_opacs_books_lents.php
  resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php
  resources/views/plugins/user/opacs/default/delivery_request.blade.php
  resources/views/plugins/user/opacs/default/opacs_edit_opac.blade.php
  resources/views/plugins/user/opacs/default/opacs_lent.blade.php
  resources/views/plugins/user/opacs/default/opacs_lentlist.blade.php
  resources/views/plugins/user/opacs/default/opacs_role_lent.blade.php
  resources/views/plugins/user/opacs/opacs_frame_edit_tab.blade.php
Labels: new feature

#1434 [FAQ]表示の順序条件にカテゴリ順を追加しました
  app/Plugins/User/Faqs/FaqsPlugin.php
  resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php
Labels: enhancement

#1418 マニュアルページへのリンク切れ修正
  .github/PULL_REQUEST_TEMPLATE.md
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  resources/views/plugins/common/errors_inline_wysiwyg.blade.php
  resources/views/plugins/manage/code/code.blade.php
  resources/views/plugins/manage/code/code_import.blade.php
  resources/views/plugins/manage/code/code_search_edit.blade.php
  resources/views/plugins/manage/page/page_import.blade.php
  resources/views/plugins/manage/user/import.blade.php
  resources/views/plugins/manage/user/list.blade.php
  resources/views/plugins/user/databases/default/databases_edit.blade.php
  resources/views/plugins/user/forms/default/forms_edit.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php
  tests/Manual/insertion/manage/page/upload/foot.txt
  tests/Manual/insertion/manage/user/foot.txt
  tests/Manual/insertion/manage/user/import/foot.txt
  tests/Manual/insertion/user/forms/editColumnDetail/foot.txt
  tests/Manual/insertion/user/learningtasks/desc.txt
  tests/Manual/insertion/user/learningtasks/foot.txt
Labels: bug

#1436 [サイト内検索]FAQプラグインの検索に対応しました
  app/Enums/SearchsTargetPlugin.php
  app/Plugins/User/Faqs/FaqsPlugin.php
Labels: enhancement

#1440 [コア]API処理でオプションプラグインも扱えるようにしました。
  app/Http/Controllers/Core/ApiController.php
Labels: ignore for release, developer update

#1442 [マニュアル]マニュアル用HTMLデータを修正しました。
  tests/Manual/insertion/user/forms/editColumnDetail/foot.txt
Labels: ignore for release, developer update

#1437 [FAQ]カテゴリでの絞り込み機能を追加しました
  app/Enums/ColorName.php
  app/Enums/FaqFrameConfig.php
  app/Enums/FaqNarrowingDownType.php
  app/Models/Common/Categories.php
  app/Plugins/User/Faqs/FaqsPlugin.php
  config/app.php
  resources/views/plugins/user/faqs/default/faqs.blade.php
  resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php
  resources/views/plugins/user/faqs/default/faqs_narrowing_down.blade.php
Labels: new feature
