Repository opensource-workshop/connect-cms, pull requests merged in 2022-11, with the labels that each got.

#1479 [管理画面] storageに書き込み権限がなければエラーメッセージを管理画面に表示する
  app/Plugins/Manage/IndexManage/IndexManage.php
  resources/views/plugins/manage/index/index.blade.php
Labels: enhancement

#1480 [nc2移行] ブログのタイトル・続きを読む・続きを隠すのタブ混入除去
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1483 [nc3移行] ブログ移行対応
  app/Models/Migration/Nc3/Nc3BlockRolePermission.php
  app/Models/Migration/Nc3/Nc3BlockSetting.php
  app/Models/Migration/Nc3/Nc3BlogEntry.php
  app/Models/Migration/Nc3/Nc3Category.php
  app/Models/Migration/Nc3/Nc3Language.php
  app/Models/Migration/Nc3/Nc3Like.php
  app/Models/Migration/Nc3/Nc3MailSetting.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1486 [nc2移行] 管理者グループの対象をコンテンツ管理者からシステム管理者に変更
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement

#1487 [データベース] メール通知の埋め込みタグに全項目タグを追加
  app/Enums/DatabaseNoticeEmbeddedTag.php
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: enhancement

#1488 [nc3移行] 汎用DB移行に対応
  app/Models/Migration/Nc2/Nc2User.php
  app/Models/Migration/Nc3/Nc3MailSetting.php
  app/Models/Migration/Nc3/Nc3MultidatabaseContent.php
  app/Models/Migration/Nc3/Nc3MultidatabaseFrameSetting.php
  app/Models/Migration/Nc3/Nc3MultidatabaseMetadata.php
  app/Models/Migration/Nc3/Nc3User.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1489 [nc3移行] 汎用DB移行に対応
  app/Models/Migration/Nc2/Nc2User.php
  app/Models/Migration/Nc3/Nc3MailSetting.php
  app/Models/Migration/Nc3/Nc3MultidatabaseContent.php
  app/Models/Migration/Nc3/Nc3MultidatabaseFrameSetting.php
  app/Models/Migration/Nc3/Nc3MultidatabaseMetadata.php
  app/Models/Migration/Nc3/Nc3User.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1490 [nc3移行] 新着の移行対応（マージ先: nc3-migrate）
  app/Models/Migration/Nc3/Nc3Plugin.php
  app/Models/Migration/Nc3/Nc3TopicFramePlugin.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1491 [nc3移行] キャビネットの移行対応（nc3-migrateにマージ）
  app/Models/Migration/Nc3/Nc3BlockRolePermission.php
  app/Models/Migration/Nc3/Nc3CabinetFile.php
  app/Models/Migration/Nc3/Nc3RolesRoom.php
  app/Models/Migration/Nc3/Nc3RoomRolePermission.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1443 [スライドショー]PDFのアップロードに対応しました
  app/Plugins/User/Slideshows/SlideshowsPlugin.php
  resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
Labels: new feature

#1475 [掲示板]枠なしテンプレートで詳細画面表示時のタイトル表示重複を改善しました
  resources/views/plugins/user/bbses/default/index.blade.php
  resources/views/plugins/user/bbses/default/show.blade.php
  resources/views/plugins/user/bbses/default/thread_show.blade.php
  resources/views/plugins/user/bbses/no_frame/show.blade.php
  resources/views/plugins/user/bbses/no_frame/thread_show.blade.php
Labels: bug

#1492 [nc3移行] 新着・キャビネットの移行対応
  app/Models/Migration/Nc3/Nc3BlockRolePermission.php
  app/Models/Migration/Nc3/Nc3CabinetFile.php
  app/Models/Migration/Nc3/Nc3Plugin.php
  app/Models/Migration/Nc3/Nc3RolesRoom.php
  app/Models/Migration/Nc3/Nc3RoomRolePermission.php
  app/Models/Migration/Nc3/Nc3TopicFramePlugin.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1477 [管理画面]ページ管理のページ移動を改善しました（セレクトボックス選択→モーダル表示ラジオボタン選択へ）
  resources/views/plugins/manage/page/page.blade.php
Labels: bug

#1484 [コア] (サイトの負荷軽減対策) robots.txtでインデックス不要な処理を拒否
  public/robots.txt
Labels: enhancement

#1482 [コア] (サイトの負荷軽減対策) 画像キャッシュ対応
  .env.example
  app/Http/Controllers/Core/UploadController.php
  app/Http/Middleware/ResponseHeader.php
  config/connect.php
  resources/views/layouts/app.blade.php
Labels: enhancement

#1493 v1.2.0 対応のマニュアル作成処理の追加です。
  app/Plugins/User/Slideshows/SlideshowsPlugin.php
  resources/views/plugins/manage/page/page.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
  tests/Browser/Manage/PageManageTest.php
  tests/Browser/User/CabinetsPluginTest.php
  tests/Browser/User/SlideshowsPluginTest.php
  tests/Browser/User/slideshow/PDF2Image.pdf
  tests/DuskTestCase.php
Labels: ignore for release

#1494 外部サービスの実行待ち時間は5秒では足りなかったので10秒に変更しました。
  tests/Browser/User/SlideshowsPluginTest.php
Labels: ignore for release

#1495 メール送信設定をマニュアルへ追記しました。
  app/Plugins/User/Databases/DatabasesPlugin.php
  resources/views/plugins/common/frame_edit_mails.blade.php
  resources/views/plugins/user/databases/description_frame_mails.blade.php
  tests/Browser/User/BbsesPluginTest.php
  tests/Browser/User/BlogsPluginTest.php
  tests/Browser/User/DatabasesPluginTest.php
Labels: ignore for release

#1496 [nc2移行] フォーム移行エクスポートでダブルクォーテーションを移行できるように対応、また改行の移行に対応
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1497 [nc3移行] 登録フォームの移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3RegistrationAnswerSummary.php
  app/Models/Migration/Nc3/Nc3RegistrationChoice.php
  app/Models/Migration/Nc3/Nc3RegistrationPage.php
  app/Models/Migration/Nc3/Nc3RegistrationQuestion.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement, ignore for release

#1499 [nc2移行] ユーザ移行エクスポートで任意項目でダブルクォーテーションを移行できるように対応2
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1500 [コア] トップページ500エラー対応
  resources/views/layouts/app.blade.php
Labels: bug

#1501 [コア] 画像キャッシュを設定しても、画像キャッシュされない不具合修正
  app/Http/Controllers/Core/UploadController.php
  app/Models/Common/Page.php
Labels: bug

#1502 [nc3移行] FAQ移行対応（nc3-migrateブランチにマージ）
  app/Enums/FaqSequenceConditionType.php
  app/Models/Migration/Nc3/Nc3FaqQuestion.php
  app/Models/User/Faqs/Faqs.php
  app/Models/User/Faqs/FaqsPosts.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
  config/app.php
Labels: enhancement, ignore for release

#1503 [nc3移行] リンクリストの移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3LinkFrameSetting.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement, ignore for release

#1504 [nc3移行] カウンターの移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3AccessCounterFrameSetting.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: ignore for release

#1505 [開発] github action に Laravel Dusk connect-cms-test 追加
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: ignore for release, developer update

#1506 [github action] warning fix
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
  .github/workflows/laravel_dusk_daily.yml
  .github/workflows/phpcs.yml
  .github/workflows/stale.yml
Labels: ignore for release, developer update

#1507 [GitHub action] dusk test bugfix
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
  .github/workflows/laravel_dusk_daily.yml
Labels: ignore for release, developer update

#1508 [github action] duskでapiテストをしないパラメータ追加
  .github/workflows/laravel_dusk_connect-cms-test.yml
  tests/Browser/User/SlideshowsPluginTest.php
  tests/DuskTestCase.php
Labels: ignore for release, developer update

#1509 PHP8.1でインポートが出来ないバグ修正
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
Labels: bug

#1510 [github action] php8.1のcomposer updateは不要になったためコメントアウト
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: ignore for release, developer update

#1511 [nc3移行] カレンダーの移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3BlockSetting.php
  app/Models/Migration/Nc3/Nc3Calendar.php
  app/Models/Migration/Nc3/Nc3CalendarEvent.php
  app/Models/Migration/Nc3/Nc3RoomRolePermission.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: ignore for release, developer update

#1512 [nc3移行] 施設予約の移行対応（nc3-migrateブランチにマージ）
  app/Models/Migration/Nc3/Nc3Category.php
  app/Models/Migration/Nc3/Nc3ReservationEvent.php
  app/Models/Migration/Nc3/Nc3ReservationLocation.php
  app/Models/Migration/Nc3/Nc3ReservationLocationsApprovalUser.php
  app/Models/Migration/Nc3/Nc3ReservationLocationsReservable.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: ignore for release, developer update
