Repository opensource-workshop/connect-cms, pull requests merged in 2023-05, with the labels that each got.

#1653 [カテゴリの設定画面] キャンセルボタンで画面遷移のみのボタンはaタグで対応
  resources/views/plugins/common/user_list_category.blade.php
Labels: ignore for release

#1655 [施設管理] 翌月表示後に施設の詳細ボタン押下で「施設の詳細データが取得できませんでした」エラー対応 OW-1861
  app/Plugins/User/Reservations/ReservationsPlugin.php
Labels: bug

#1654 [データベース]検索結果として返却する「登録日」「登録者」を修正・変更しました
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: plugin(database)

#1662 [ページ管理] 外部ページインポートにHTML2CMS移行機能を追加
  app/Enums/WebsiteType.php
  app/Plugins/Manage/PageManage/PageManage.php
  app/Traits/Migration/MigrationExportHtmlPageTrait.php
  config/app.php
  resources/views/plugins/manage/page/migration_order.blade.php
Labels: new feature

#1664 bugfix: [ページ管理-インポート] 参照PATHの補填処理でディレクトリインストールも考慮するよう修正
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1665 [サイト内検索]検索結果に本文を表示するようにしました
  app/Plugins/User/Bbses/BbsesPlugin.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  app/Plugins/User/Contents/ContentsPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Faqs/FaqsPlugin.php
  app/Plugins/User/Searchs/SearchsPlugin.php
  resources/views/plugins/user/searchs/default/searchs_result.blade.php
Labels: enhancement, plugin(search)

#1666 [データベース]絞り込みOFF＋並べ替えONで絞込みプルダウンが表示される不具合を修正しました
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
Labels: bug, plugin(database)

#1668 [サイト内検索] 設置画面（新規/変更）バリデートエラー時にラジオ項目の入力値巻き戻りを修正
  resources/views/plugins/user/searchs/default/searchs_edit_search.blade.php
Labels: bug

#1670 fix: [ブログ] 編集権限が許可されたユーザであっても重要記事マークが見えないのを修正しました
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_show.blade.php
  resources/views/plugins/user/blogs/designbase/blogs.blade.php
  resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
Labels: bug

#1676 [移行ツール] NC3移行バグ修正
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1678 [ブログ] 未ログイン状態で一覧／参照画面を照会するとエラーになる事象を修正しました。
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_show.blade.php
  resources/views/plugins/user/blogs/designbase/blogs.blade.php
  resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
Labels: bug

#1679 [サイト管理] NC3移行後にサイト設計書出力すると500エラーになるバグ修正
  app/Plugins/Manage/SiteManage/SiteManage.php
Labels: bug

#1680 [ユーザ管理] 最後のシステム管理者保持者は削除させない・システム管理者権限を外させない対応
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/auth/registe_form.blade.php
Labels: enhancement
