Repository opensource-workshop/connect-cms, pull requests merged in 2023-11, with the labels that each got.

#1873 [wysiwyg] page_id = nullだとDBに登録できないため見直し
  resources/views/plugins/common/wysiwyg.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
Labels: ignore for release

#1862 [コア] メール設定エラー時にわかりやすいメッセージを表示
  app/Exceptions/Handler.php
  resources/views/errors/mail_setting_error.blade.php
  resources/views/plugins/common/error_system_mail_setting.blade.php
  resources/views/plugins/common/frame_edit_mails.blade.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_mail.blade.php
Labels: enhancement

#1874 [メール] グループから通知するメールアドレス取得する処理を他でも使えるようfunction化
  app/Models/Common/BucketsMail.php
Labels: developer update

#1875 [いいね] フレームID取得処理の統一
  resources/views/plugins/common/like.blade.php
Labels: developer update

#1876 [掲示板] タイトル行でEnterキー押下でフォーム送信を防止 OW-2070
  .env.example
  config/connect.php
  resources/lang/en/messages.php
  resources/lang/ja/messages.php
  resources/views/plugins/user/bbses/default/edit.blade.php
  resources/views/plugins/user/bbses/default/index.blade.php
Labels: enhancement

#1880 [自動テスト] 掲示板, 登録時の確認ダイアログ追加に伴う自動テストの修正
  tests/Browser/User/BbsesPluginTest.php
Labels: ignore for release

#1852 [移行]DatabasesTruncate処理を修正
  app/Traits/Migration/MigrationTrait.php
Labels: bug, migration

#1799 [テーマ管理]WYSIWYGのテンプレート編集機能を追加しました。
  app/Plugins/Manage/ThemeManage/ThemeManage.php
  resources/views/plugins/manage/theme/theme.blade.php
  resources/views/plugins/manage/theme/theme_template_edit.blade.php
Labels: additional request

#1882 [ブログ] 投稿者絞込機能追加 OW-2072
  app/Enums/BlogFrameConfig.php
  app/Enums/BlogNarrowingDownTypeForCreatedId.php
  app/Models/User/Blogs/Blogs.php
  app/Models/User/Blogs/BlogsPosts.php
  app/Models/User/Blogs/BlogsPostsTags.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  config/app.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/blogs/default/include_narrowing_down.blade.php
Labels: new feature

#1883 [ブログ] 投稿者絞込機能追加2 OW-2072
  app/Enums/BlogFrameConfig.php
  app/Enums/BlogNarrowingDownTypeForCreatedId.php
  app/Models/User/Blogs/Blogs.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  database/migrations/2023_11_15_175748_add_narrowing_down_type_for_created_id_from_blogs.php
  resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/blogs/default/include_narrowing_down_for_created_id.blade.php
Labels: new feature

#1884 [ブログ] 表示条件設定に 自身の投稿のみ を追加 OW-2076
  app/Enums/BlogFrameScope.php
  app/Models/User/Blogs/BlogsPosts.php
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/blogs/default/include_scope.blade.php
  resources/views/plugins/user/blogs/designbase/blogs.blade.php
Labels: new feature

#1885 [フレーム設定] 公開設定に ログイン後表示 を追加 OW-2077
  app/Enums/ContentOpenType.php
  app/Models/Common/Frame.php
  resources/views/core/cms_frame_edit.blade.php
  resources/views/core/cms_frame_header.blade.php
Labels: new feature

#1889 [ユーザ管理] 同意型の詳細でチェックボックスの名称等を更新すると500エラーになる不具合修正
  app/Plugins/Manage/UserManage/UserManage.php
Labels: bug

#1890 [移行] ブログの続きを読む内容のリンクチェックで参照変数が間違っていたため修正
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1892 カウンター, botチェックを他でも使えるようにUtilitiesに切り出し
  app/Plugins/User/Counters/CountersPlugin.php
  app/Utilities/Request/RequestUtils.php
Labels: developer update
