Repository opensource-workshop/connect-cms, pull requests merged in 2023-10, with the labels that each got.

#1843 [wysiwygエディタ]画像編集時の詳細設定タブを追加しました
  resources/views/plugins/common/wysiwyg.blade.php
Labels: enhancement

#1822 [データベース]全文検索機能を追加しました
  app/Models/User/Databases/DatabasesInputs.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databases/DatabasesTool.php
  database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
  resources/views/plugins/user/databases/default/databases_edit_database.blade.php
Labels: enhancement, plugin(database)

#1837 [データベース]検索窓としての表示設定を可能にしました
  app/Enums/DatabaseFrameConfig.php
  app/Models/Common/Frame.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
Labels: enhancement, plugin(database)

#1838 [データベース]急上昇ワードを表示する機能を追加しました
  app/Enums/DatabaseFrameConfig.php
  app/Models/User/Databases/DatabasesSearchedWord.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databases/DatabasesTool.php
  database/migrations/2023_09_12_182442_add_save_search_word_to_databases.php
  database/migrations/2023_09_12_183229_create_databases_searched_words.php
  resources/views/plugins/user/databases/default/databases_edit_database.blade.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
Labels: enhancement, plugin(database)

#1839 [データベース]項目の型に表示件数型を追加しました
  app/Enums/DatabaseColumnType.php
  app/Enums/DatabaseNoticeEmbeddedTag.php
  app/Enums/DatabaseSearcherSortType.php
  app/Enums/DatabaseSortFlag.php
  app/Models/User/Databases/DatabasesColumns.php
  app/Models/User/Databases/DatabasesInputs.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
  database/migrations/2023_09_20_132746_add_views_to_databases_inputs.php
  resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php
  resources/views/plugins/user/databases/default/databases_include_value.blade.php
Labels: enhancement, plugin(database)

#1845 [データベース]並び替え設定がない場合にシステムエラーとなる事象を修正しました
  app/Plugins/User/Databases/DatabasesPlugin.php
  tests/Browser/User/DatabasesPluginTest.php
Labels: bug, ignore for release

#1849 [コア]UserFactoryを最新化しました
  app/User.php
  database/factories/UserFactory.php
Labels: developer update

#1846 [サイト管理] 使用容量 画面追加
  app/Plugins/Manage/SiteManage/SiteManage.php
  app/Utilities/File/FileUtils.php
  resources/views/plugins/manage/site/site_manage_tab.blade.php
  resources/views/plugins/manage/site/total.blade.php
Labels: new feature

#1850 [PTASeeder] 実行時エラーの対応
  database/seeders/PTASeeder.php
Labels: developer update

#1851 [データベース]急上昇ワードを押下しても遷移しない問題を修正しました
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
Labels: bug, plugin(database)

#1856 [コア]フレームのヘッダーにプラグインが編集可能であることを表すclassを追加しました
  resources/views/core/cms_frame_header.blade.php
Labels: core, developer update

#1857 [コア]フレーム共通ヘッダーbladeの処理を改善しました
  resources/views/core/cms_frame_header.blade.php
Labels: core, ignore for release

#1858 2.7.5に1.12.1をマージし2.8.1を作ります
  app/Enums/DatabaseColumnType.php
  app/Enums/DatabaseFrameConfig.php
  app/Enums/DatabaseNoticeEmbeddedTag.php
  app/Enums/DatabaseSearcherSortType.php
  app/Enums/DatabaseSortFlag.php
  app/Models/Common/Frame.php
  app/Models/User/Databases/DatabasesColumns.php
  app/Models/User/Databases/DatabasesInputs.php
  app/Models/User/Databases/DatabasesSearchedWord.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databases/DatabasesTool.php
  app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
  config/version.php
  database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
  database/migrations/2023_09_12_182442_add_save_search_word_to_databases.php
  database/migrations/2023_09_12_183229_create_databases_searched_words.php
  database/migrations/2023_09_20_132746_add_views_to_databases_inputs.php
  resources/views/plugins/common/wysiwyg.blade.php
  resources/views/plugins/user/databases/default/databases_edit_database.blade.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
  resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php
  resources/views/plugins/user/databases/default/databases_include_value.blade.php
Labels: ignore for release

#1863 [コア] package.jsonからpostcssライブラリを除去
  package-lock.json
  package.json
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
Labels: developer update

#1865 [データベース検索]ウィジウィグ型にaタグが含まれるとHTMLが崩れる問題を修正しました
  resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
Labels: bug

#1866 [データベース検索]並べ替え条件にランダムを追加しました
  app/Enums/DatabaseSearcherSortType.php
  app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
Labels: enhancement

#1867 [データベース]検索をGETメソッドでも実行可能にしました
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: plugin(database), developer update

#1868 [入力エラー] ファイルアップロードで入力エラー時にファイル参照欄を赤線で囲う対応の見直し
  resources/views/plugins/manage/page/page_import.blade.php
  resources/views/plugins/manage/site/favicon.blade.php
  resources/views/plugins/manage/user/import.blade.php
  resources/views/plugins/user/cabinets/default/index.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php
  resources/views/plugins/user/photoalbums/default/edit_contents.blade.php
  resources/views/plugins/user/photoalbums/default/edit_video.blade.php
  resources/views/plugins/user/photoalbums/default/index_head.blade.php
Labels: enhancement

#1870 [データベース]表示件数型が出力されない問題を対応しました
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1872 [ログ設定] ログ設定でURIを記録する設定をした場合、長いURIで500エラーが出る問題に対応
  database/migrations/2023_10_31_090932_change_uri_length_from_app_logs.php
Labels: bug
