Repository opensource-workshop/connect-cms, pull requests merged in 2023-02, with the labels that each got.

#1568 [メール送信] .envのQUEUE_CONNECTION=database＋php-cgiで掲示板等のメールが送れなかった不具合に対応 OW-1704
  .env.example
  app/Plugins/User/UserPluginBase.php
  config/connect.php
Labels: bug

#1571 [検索] データベースに１つでも絞り込み条件が設定されていると、全データベース絞り込まれて検索結果にでてこない不具合修正
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databases/DatabasesTool.php
Labels: bug

#1572 [データベース] phpcs fix.
  app/Plugins/User/Databases/DatabasesTool.php
Labels: ignore for release

#1575 [github action] Install Jp fontで処理が止まるため見直し
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: ignore for release

#1577 [docker] dockerイメージ宣言箇所にコメント追記
  docker/app/Dockerfile
Labels: ignore for release

#1578 オプション開発用のcomposerです。
  composer-option.json
  composer-option.lock
Labels: ignore for release

#1582 オプション用composer関係ファイルをgitirnoreします。
  .gitignore
Labels: ignore for release

#1587 [nc2移行] アンケートの移行対応
  app/Models/Migration/Nc2/Nc2QuestionnaireAnswer.php
  app/Models/Migration/Nc2/Nc2QuestionnaireBlock.php
  app/Models/Migration/Nc2/Nc2QuestionnaireChoice.php
  app/Models/Migration/Nc2/Nc2QuestionnaireQuestion.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
Labels: enhancement

#1579 [コア] sessionのexpire_on_closeを.envで設定できるように対応
  .env.example
  config/session.php
Labels: enhancement

#1581 [コア]利用パッケージにGuzzleを追加しました
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
Labels: developer update

#1583 [コア]利用パッケージにGuzzleを追加しました（Connect-CMS 2）
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
Labels: developer update

#1591 [フォーム] アンケートモードで項目設定で型が変更できない不具合修正
  resources/views/plugins/user/forms/default/forms_edit_row2.blade.php
Labels: bug

#1592 [システム管理] 「メール設定」の入力項目に null という文字列が付く不具合の修正
  app/Plugins/Manage/SystemManage/SystemManage.php
Labels: bug
