Repository opensource-workshop/connect-cms, pull requests merged in 2023-06, with the labels that each got.

#1682 [ユーザ管理] 最後のシステム管理者保持者から編集で利用不可・仮削除にしたときの入力チェック追加
  app/Plugins/Manage/UserManage/UserManage.php
Labels: enhancement

#1681 [ユーザ管理] システム管理者権限持ちユーザはシステム管理者のみ編集可
  app/Plugins/Manage/UserManage/UserManage.php
  app/User.php
  resources/views/plugins/manage/user/list.blade.php
Labels: enhancement

#1683 [移行ツール] NC2・3移行エクスポート, 固定記事の置換オプションに対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1685 [移行ツール] nc3の移行設定サンプルからslideshowsの移行設定に抜けがあったため追記
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: bug

#1686 [フォーム] php80＋任意の単一選択１つのみのフォーム＋未選択で確認画面にいくと500エラーになるバグ修正
  resources/views/plugins/user/forms/default/forms_confirm_column_checkbox.blade.php
  resources/views/plugins/user/forms/default/forms_confirm_column_radio.blade.php
  resources/views/plugins/user/forms/default/forms_confirm_column_select.blade.php
Labels: bug

#1687 [コア] バケツ編集画面でプレビューモードにすると権限なしエラーが出るバグ修正
  resources/views/layouts/app.blade.php
Labels: bug

#1693 [移行ツール] nc3移行エクスポートでメニューのフレームタイトルを残す設定を追加
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1694 [移行ツール] nc3移行エクスポートでページレイアウトを全件出力する設定を追加
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: enhancement

#1697 [コア]ディレクトリインストールの場合にapp.cssとapp.jsが読み込まれない問題を修正しました
  resources/views/layouts/app.blade.php
Labels: bug

#1700 [移行ツール] nc3移行エクスポート, NC3お知らせの限定公開From-Toのいずれかが空の場合、インポート時にエラーで落ちるバグ対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#1701 [フレーム] 公開日時From, Toにtimestamp型の範囲内の入力チェックを追加
  app/Http/Controllers/Core/FrameCore.php
Labels: bug

#1702 [ブログ] 観覧者に表示件数リストを表示する設定追加
  app/Models/User/Blogs/Blogs.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  database/migrations/2023_06_12_102116_add_use_view_count_spectator_from_blogs.php
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php
  resources/views/plugins/user/blogs/default/include_view_count_spectator.blade.php
  resources/views/plugins/user/blogs/designbase/blogs.blade.php
Labels: enhancement

#1703 [移行ツール] NC2・3から移行する時は、常に表示件数リストを表示ONで移行
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement

#1706 [ユーザ管理] システム管理者権限付与は、システム管理者のみ可に修正
  resources/views/auth/registe_form.blade.php
Labels: enhancement

#1707 [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、ページ階層が移行後に再現するよう対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: enhancement

#1708 [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、ページ順番を移行後に再現するよう対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: enhancement

#1710 [ページ送り] ページ送り（paginate）が中央エリアでもフレーム幅以上になるとはみ出るため、flex-wrapで折り返しするよう対応
  resources/views/vendor/pagination/bootstrap-4.blade.php
Labels: bug

#1711 [移行ツール] NC3のFAQを移行した時、カテゴリの絞り込み機能を常時ONで移行する
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement

#1712 [ブログ] カテゴリの絞り込み機能追加
  app/Enums/BlogNarrowingDownType.php
  app/Models/User/Blogs/Blogs.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  config/app.php
  database/migrations/2023_06_14_005653_add_narrowing_down_type_from_blogs.php
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php
  resources/views/plugins/user/blogs/default/include_narrowing_down.blade.php
  resources/views/plugins/user/blogs/default/include_view_count_spectator.blade.php
  resources/views/plugins/user/blogs/designbase/blogs.blade.php
Labels: enhancement

#1713 [移行ツール] NC2・3からブログを移行する時は、常にカテゴリの絞り込み機能ONで移行
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#1718 [移行ツール] インポート時にNC3のブログ-一覧-カテゴリ指定リンクをConnectのリンクに自動置換対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#1719 [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、汎用DBの記事が移行されない不具合の対応
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#1720 [移行ツール] @updateのpage.iniは@update処理に対応してないためサンプル削除
  app/Traits/Migration/sample/migration/@update/pages/0007/page.ini
Labels: developer update

#1723 [移行ツール] NC3エクスポート時にサイト全体ーヘッダーー非公開のお知らせの、非公開が公開されて移行されるバグ修正
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#1724 [祝日管理] 2025年を登録しても一覧に表示できないバグ修正 OW-1907
  app/Plugins/Manage/HolidayManage/HolidayManage.php
  resources/views/plugins/manage/holiday/index.blade.php
Labels: bug

#1714 [コア－共通] 新着情報プラグイン用のポリフィル対応を除去
  resources/views/layouts/app.blade.php
Labels: developer update

#1727 [移行ツール] NC3移行エクスポート時、Wysiwyg内HTMLからNC3絵文字を削除
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Utilities/Migration/MigrationUtils.php
Labels: enhancement

#1673 [サイト内検索]defaultテンプレート、タイトル表示バグ、カテゴリ表示バグ、クラス名付与の修正を行いました。
  resources/views/plugins/user/searchs/default/searchs_result.blade.php
Labels: bug, plugin(search)

#1729 [移行ツール] NC3移行エクスポート時にNC3絵文字の削除で不要に前後の文字や画像を消す不具合を修正
  app/Utilities/Migration/MigrationUtils.php
Labels: bug

#1728 [コア] 管理画面系bladeでUndefined variableエラーが起こっても、エラー画面が表示されないバグの修正
  app/Enums/PermissionType.php
  app/Enums/ShowType.php
  app/Models/Common/ConnectCarbon.php
  app/Models/Common/Group.php
  app/Models/Common/YasumiHoliday.php
  app/Plugins/Manage/AuthManage/AuthManage.php
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/MessageManage/MessageManage.php
  app/Plugins/Manage/ReservationManage/ReservationManage.php
  app/Plugins/Manage/SiteManage/SiteManage.php
  app/Plugins/Manage/ThemeManage/ThemeManage.php
  app/Plugins/PluginBase.php
  resources/views/plugins/common/wysiwyg.blade.php
  resources/views/plugins/manage/code/code_download.blade.php
  resources/views/plugins/manage/code/code_search_edit.blade.php
  resources/views/plugins/manage/code/display.blade.php
  resources/views/plugins/manage/code/help_message.blade.php
  resources/views/plugins/manage/code/help_message_edit.blade.php
  resources/views/plugins/manage/holiday/index.blade.php
  resources/views/plugins/manage/message/message.blade.php
  resources/views/plugins/manage/page/role.blade.php
  resources/views/plugins/manage/reservation/edit.blade.php
  resources/views/plugins/manage/reservation/edit_column_set.blade.php
  resources/views/plugins/manage/site/analytics.blade.php
  resources/views/plugins/manage/site/document.blade.php
  resources/views/plugins/manage/site/meta.blade.php
  resources/views/plugins/manage/site/page_error.blade.php
  resources/views/plugins/manage/site/pdf/auth_base.blade.php
  resources/views/plugins/manage/site/pdf/auth_ldap.blade.php
  resources/views/plugins/manage/site/pdf/auth_netcommons2.blade.php
  resources/views/plugins/manage/site/pdf/base_analytics.blade.php
  resources/views/plugins/manage/site/pdf/base_error.blade.php
  resources/views/plugins/manage/site/pdf/base_favicon.blade.php
  resources/views/plugins/manage/site/pdf/base_language.blade.php
  resources/views/plugins/manage/site/pdf/base_layout.blade.php
  resources/views/plugins/manage/site/pdf/base_main.blade.php
  resources/views/plugins/manage/site/pdf/base_meta.blade.php
  resources/views/plugins/manage/site/pdf/base_wysiwyg.blade.php
  resources/views/plugins/manage/site/pdf/contact.blade.php
  resources/views/plugins/manage/site/pdf/cover.blade.php
  resources/views/plugins/manage/site/pdf/log_main.blade.php
  resources/views/plugins/manage/site/pdf/massage_first.blade.php
  resources/views/plugins/manage/site/pdf/service_base.blade.php
  resources/views/plugins/manage/site/pdf/service_face.blade.php
  resources/views/plugins/manage/site/pdf/service_pdf.blade.php
  resources/views/plugins/manage/site/pdf/system_log.blade.php
  resources/views/plugins/manage/site/pdf/system_server.blade.php
  resources/views/plugins/manage/site/pdf/user_regist.blade.php
  resources/views/plugins/manage/theme/theme_generate.blade.php
  resources/views/plugins/manage/user/bulk_delete.blade.php
  resources/views/plugins/manage/user/list_include_value.blade.php
  tests/Browser/Manage/UserManageTest.php
Labels: bug

#1731 [自動テスト] API管理,テーマ管理,サイト管理のgithub action testで表示が遅いのか、セレクターが見つからなくてエラーになるため、ちょっと待つ処理を追加
  tests/Browser/Manage/ApiManageTest.php
  tests/Browser/Manage/SiteManageTest.php
  tests/Browser/Manage/ThemeManageTest.php
Labels: ignore for release

#1732 [連番管理] 連番取得functionの汎用化
  app/Models/Common/Numbers.php
  app/Plugins/PluginBase.php
Labels: developer update

#1733 [メールの埋め込みタグ] 共通のメール設定画面の説明を任意に変更できるように対応
  app/Enums/NoticeEmbeddedTag.php
  resources/views/plugins/common/description_frame_mails_common.blade.php
Labels: developer update

#1734 [フォーム] 閲覧パスワード設定追加
  app/Enums/FormAccessLimitType.php
  app/Models/User/Forms/Forms.php
  app/Plugins/User/Forms/FormsPlugin.php
  config/app.php
  database/migrations/2023_06_26_094629_add_access_limit_type_form_password_from_forms.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  resources/views/plugins/user/forms/default/index_password.blade.php
Labels: new feature

#1735 [API共通] Slackリクエスト検証の共通処理を追加＆connect設定値にSLACK_SIGNING_SECRETを追加
  app/Plugins/Api/ApiPluginBase.php
  config/connect.php
Labels: enhancement, developer update

#1739 [FrameConfig] saveFrameConfigs()時、checkbox_separatorを指定できるように対応, また配列の空要素を削除するよう対応
  app/Models/Core/FrameConfig.php
Labels: developer update

#1737 [コア] 既存プラグインにオプションテンプレートを追加できるよう対応
  app/Http/Controllers/Core/DefaultController.php
  app/Plugins/User/UserPluginBase.php
Labels: developer update

#1738 [新着情報] オプションプラグインも指定できるように対応
  app/Enums/WhatsnewsTargetPlugin.php
  app/Models/User/Whatsnews/Whatsnews.php
  app/Plugins/User/Bbses/BbsesPlugin.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/UserPluginBase.php
  app/Plugins/User/Whatsnews/WhatsnewTargetPluginTool.php
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
  config/app.php
  resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
Labels: developer update

#1740 [新着情報] 入力エラー時にラジオの選択が維持されないバグ修正
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
  resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
Labels: bug

#1743 [アップロードファイル管理] 一時保存を更新してファイルを削除せず非公開にできるように対応2 OWSP-806
  app/Plugins/Manage/UploadfileManage/UploadfileManage.php
  resources/views/plugins/manage/uploadfile/edit.blade.php
Labels: enhancement
