Repository opensource-workshop/connect-cms, pull requests merged in 2023-07, with the labels that each got.

#1744 [移行ツール] NC3移行エクスポートのトップページ・ルームトップのヘッダ・フッター・左・右エリアのフレーム出力見直し
  app/Models/Migration/Nc3/Nc3Frame.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
Labels: bug

#1746 [移行ツール] NC2移行エクスポート時、NC2絵文字を自動削除
  app/Traits/Migration/MigrationTrait.php
  app/Utilities/Migration/MigrationUtils.php
Labels: developer update

#1747 [移行ツール] NC2移行エクスポート時、メニューのフレームタイトルを消さずに残すオプション追加
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
Labels: developer update

#1748 サンプルシェルの不要な記号を削除, 既に削除済みのマイグレーションファイルの除外指定を削除
  sync_dev_2_option_private.sh.example
  sync_option_private_2_dev.sh.example
Labels: ignore for release

#1749 [API管理] php8.0で管理画面が開けないバグ修正
  resources/views/plugins/manage/api/api.blade.php
Labels: bug

#1751 [管理画面等] php8.1対応
  app/Enums/CsvCharacterCode.php
  app/Models/Common/Page.php
  app/Models/Core/Configs.php
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Utilities/Csv/CsvUtils.php
  resources/views/auth/registe_form.blade.php
  resources/views/plugins/manage/reservation/edit.blade.php
  resources/views/plugins/manage/reservation/index.blade.php
  tests/Browser/User/ReservationsPluginTest.php
Labels: bug

#1754 [アップロードファイル] (beta)ユーザパブリックファイルの一覧画面追加
  .env.example
  app/Models/Common/Uploads.php
  app/Plugins/Manage/UploadfileManage/UploadfileManage.php
  app/Utilities/File/FileUtils.php
  config/app.php
  config/connect.php
  resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php
  resources/views/plugins/manage/uploadfile/userdir_public.blade.php
Labels: developer update

#1758 [移行ツール] NC3移行エクスポート＋nc3.2.0より古い場合、ページの階層がうまく移行できない不具合修正
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#1760 [スライダー] 項目設定画面をlgでもPC表示と同じにする修正＋スマホ表示の見直し
  resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
Labels: enhancement

#1761 [リンクリスト] 登録変更時にメッセージを表示＋登録後は一覧画面に遷移するよう見直し
  app/Plugins/User/Linklists/LinklistsPlugin.php
  resources/views/plugins/user/linklists/default/edit.blade.php
  resources/views/plugins/user/linklists/default/index.blade.php
Labels: enhancement

#1763 [新着情報] オプションプラグインのもっと見るが機能しないバグ修正
  app/Models/Core/Plugins.php
  app/Plugins/User/Whatsnews/WhatsnewTargetPluginTool.php
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
Labels: bug

#1764 [新着情報] もっと見る時のclassnameを初期表示と同じになるよう対応
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
Labels: bug

#1674 [データベース]項目名非表示フラグが効かないテンプレートに対して、フラグが利用できるように修正しました。
  resources/views/plugins/user/databases/design-table-dl/databases.blade.php
  resources/views/plugins/user/databases/table/databases.blade.php
Labels: bug, plugin(database)

#1766 [サイト管理]設計書出力にNC3移行データの出力を追加しました
  app/Plugins/Manage/SiteManage/SiteManage.php
  resources/views/plugins/manage/site/pdf/migrate_main.blade.php
Labels: manage(site), additional request, developer update

#1767 [NC3移行]データエクスポート時（redo時）に@insertディレクトリを削除する修正を入れました
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: migration, developer update

#1769 [コア] twitter・facebookボタンの汎用化対応
  resources/views/plugins/common/facebook.blade.php
  resources/views/plugins/common/twitter.blade.php
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/blogs/default/blogs_show.blade.php
  resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
Labels: developer update

#1770 [施設予約] カレンダー月表示データの生成を汎用化
  app/Plugins/User/Reservations/ReservationsPlugin.php
  app/Traits/ConnectCommonTrait.php
Labels: developer update

#1771 [施設予約] 予約終了時間の 00:00 を 24:00 に自動変換がされないパターンに対応
  resources/views/plugins/user/reservations/default/edit_booking.blade.php
Labels: bug

#1773 bugfix: 施設管理, 利用終了時間の 00:00 を 24:00 に自動変換がされないパターンに対応 OW-1940
  resources/views/plugins/manage/reservation/edit.blade.php
Labels: bug

#1776 [管理画面]サイト管理NC3移行データ出力を修正しました
  app/Plugins/Manage/SiteManage/SiteManage.php
Labels: bug, manage(site)

#1778 [フォーム] 閲覧パスワードON＋php8でパスワード入力後に500エラーになるバグ修正
  resources/views/plugins/user/forms/default/forms_input_date.blade.php
  resources/views/plugins/user/forms/default/forms_input_mail.blade.php
  resources/views/plugins/user/forms/default/forms_input_text.blade.php
  resources/views/plugins/user/forms/default/forms_input_textarea.blade.php
  resources/views/plugins/user/forms/default/forms_input_time.blade.php
  resources/views/plugins/user/forms/default/forms_input_time_from_to.blade.php
Labels: bug

#1781 [移行ツール] NC2移行エクスポートの汎用DB, カスタマイズ順の移行に対応
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#1780 [フレーム] ログイン後非表示機能を追加 OW-1656
  app/Enums/ContentOpenType.php
  app/Models/Common/Frame.php
Labels: enhancement

#1783 [NC3移行]カレンダータイトルの不要文字削除処理を追加
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, migration
