Repository opensource-workshop/connect-cms, pull requests merged in 2023-01, with the labels that each got.

#1541 [データベース] タイトル指定にした項目を空でデータ登録/更新するとエラーになる不具合対応
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1534 Bugfix: ファイル型アップロード時のセッション作成処理を修正
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1543 [フォーム] 登録時にファイル型データをアップロードした状態で入力チェックエラーになると500エラーになる不具合の修正
  app/Plugins/User/Forms/FormsPlugin.php
Labels: bug

#1545 [施設予約] 終了指定日の前日までしか予約されないバグの修正
  app/Plugins/User/Reservations/ReservationsPlugin.php
Labels: bug

#1544 [フレーム] 左エリアにフレームタイトル空で「このページのみ表示する」を設定すると、歯車ボタンが押せなくなる不具合修正 OW-1656
  resources/views/core/cms_frame_header.blade.php
Labels: bug

#1540 NetCommons2移行、システム設定、外部サービス設定のマニュアルを追記しました。
  app/Models/Core/Dusks.php
  app/Plugins/Manage/IndexManage/IndexManage.php
  app/Plugins/Manage/PageManage/PageManage.php
  app/Plugins/Manage/SiteManage/SiteManage.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  app/Plugins/User/Contents/ContentsPlugin.php
  database/migrations/2022_12_30_182228_add_spec_to_dusks_table.php
  resources/views/manual/index.blade.php
  resources/views/manual/spec/pdf_cover.blade.php
  resources/views/manual/spec/txt.blade.php
  tests/Browser/Manage/MigrationManageTest.php
  tests/Browser/Manage/ServiceManageTest.php
  tests/Browser/Manage/SystemManageTest.php
  tests/Browser/User/ContentsPluginTest.php
  tests/DuskTestCase.php
  tests/Manual/src/SpecOutput.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1546 [コア：アップロードファイル] ファイルの削除機能を追加しました
  app/Http/Controllers/Core/UploadController.php
  app/Plugins/Manage/UploadfileManage/UploadfileManage.php
  resources/views/plugins/manage/uploadfile/edit.blade.php
  resources/views/plugins/manage/uploadfile/index.blade.php
Labels: new feature

#1548 マニュアルに機能一覧を追加しました。
  app/Models/Core/Dusks.php
  resources/views/manual/common/badge_menu.blade.php
  resources/views/manual/function.blade.php
  resources/views/manual/function/cover.blade.php
  resources/views/manual/function/function.blade.php
  tests/Browser/Blueprint/IndexBlueprintTest.php
  tests/Browser/Blueprint/PageBlueprintTest.php
  tests/Browser/Blueprint/RoleBlueprintTest.php
  tests/Browser/Blueprint/ServiceBlueprintTest.php
  tests/Manual/insertion/manage/function_foot.txt
  tests/Manual/insertion/mypage/function_foot.txt
  tests/Manual/insertion/mypage/function_foot_pdf.txt
  tests/Manual/insertion/user/function_foot.txt
  tests/Manual/insertion/user/function_foot_pdf.txt
  tests/Manual/src/FunctionListPdf.php
  tests/Manual/src/ManualOutput.php
  tests/Manual/src/ManualPdf.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1550 マニュアルにテーマチェンジャーを追加＆細かい修正をしました。
  app/Plugins/Manage/UploadfileManage/UploadfileManage.php
  app/Plugins/User/Themechangers/ThemechangersPlugin.php
  resources/views/plugins/user/themechangers/default/themechangers.blade.php
  tests/Browser/User/ThemechangersPluginTest.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1551 マニュアルPDFの出力方式を増やしました。
  app/Plugins/User/Themechangers/ThemechangersPlugin.php
  resources/views/manual/index.blade.php
  resources/views/manual/pdf/cover.blade.php
  tests/Browser/Common/WysiwygTest.php
  tests/DuskTestCase.php
  tests/Manual/src/ManualPdf.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1552 消し忘れ対応
  resources/views/manual/index.blade.php
Labels: ignore for release

#1553 機能一覧PDFの追加データの漏れに対応しました。
  tests/Manual/insertion/manage/function_foot_pdf.txt
Labels: ignore for release

#1554 開発予定にRSSが抜けていたので追記しました。
  tests/Manual/insertion/user/function_foot.txt
  tests/Manual/insertion/user/function_foot_pdf.txt
Labels: ignore for release

#1557 ログイン失敗時のロック機能についてマニュアルに追記しました。
  tests/Browser/Common/LoginLockTest.php
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1558 自動ユーザ登録時に説明文章があると、autofocusが邪魔をして、説明文が初期状態で表示されなくなるため、省きます。
  resources/views/auth/registe_form.blade.php
Labels: core

#1555 [コア]Laravel8.x から Laravel9.x にアップグレードしました
  .github/workflows/phpcs.yml
  app/Http/Middleware/TrustProxies.php
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
  config/database.php
  config/filesystems.php
  resources/lang/en/validation.php
  resources/lang/ja/validation.php
Labels: developer update

#1559 [ユーザ管理] php8.1＋自動ユーザ登録設定の登録時の500エラーに対応
  app/Plugins/Manage/UserManage/UserManage.php
Labels: bug

#1562 [サイト全体]ナビバーのサイト名が長い場合にウィンドウ幅に合わせて省略するようにしました
  public/css/connect.css
Labels: enhancement

#1547 [コア]FrameConfigの登録処理について、複数選択（チェックボックス）の設定値に対応しました
  app/Models/Core/FrameConfig.php
Labels: ignore for release

#1566 [.gitignore] .vscode配下と/resources/views/mail_option/配下をgit管理から除外
  .gitignore
Labels: ignore for release

#1564 [システム管理] エラーログ設定画面を廃止して、出力ログを１本化する OW-1684
  app/Plugins/Manage/SystemManage/SystemManage.php
  app/Plugins/User/UserPluginBase.php
  resources/views/plugins/manage/system/system_tab.blade.php
  tests/Browser/Manage/SystemManageTest.php
Labels: bug

#1537 [サイト管理] 言語設定の削除処理が漏れていたので追加しました。
  app/Plugins/Manage/SiteManage/SiteManage.php
Labels: bug

#1561 [robots.txt] 同一ドメイン＋nc2の短縮URLでnc2->cc移行時のgoogle image bot等へのインデックス除外対応
  public/robots.txt
Labels: enhancement

#1565 [.env] LOG_CHANNELをdaily(level=debug) => daily_info(level=info)に修正
  .env.example
Labels: enhancement
