Repository opensource-workshop/connect-cms, pull requests merged in 2023-12, with the labels that each got.

#1895 [マイグレーション] MariaDBは5.6以上でFULLTEXT対応
  database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
Labels: enhancement

#1896 [開発ツール] sync_option_private_2_dev.sh.exampleのモデルとビューにディレクトリがなければ作成するコマンド追加
  sync_option_private_2_dev.sh.example
Labels: developer update

#1897 [自動ユーザ登録設定] メールの埋め込みタグ説明で不要な { 表示削除
  resources/views/plugins/manage/user/description_frame_mails.blade.php
Labels: bug

#1900 [新着情報] card_04_top_thumbnailテンプレート追加
  resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/card_04_top_thumbnail/whatsnews.blade.php
Labels: new feature

#1902 [マイページ] 管理機能 or コンテンツ権限なしでマイページ表示すると、コンテンツ画面へが表示されないバグ修正
  resources/views/layouts/app.blade.php
Labels: bug

#1893 [コア]Factoryクラスを追加しました
  app/Models/Common/Group.php
  app/Models/Common/GroupUser.php
  app/Models/Common/Uploads.php
  config/app.php
  database/factories/Common/GroupFactory.php
  database/factories/Common/GroupUserFactory.php
  database/factories/Common/UploadsFactory.php
Labels: developer update

#1903 [メニュー] ディレクトリ展開式デザイン用テンプレートにページ詳細のクラス名をliタグに適用
  resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php
Labels: enhancement

#1905 [ユーザ管理] 検索時とcolumns_set_idをURL等で指定時には、表示ページ数をクリアする対応
  app/Plugins/Manage/UserManage/UserManage.php
Labels: enhancement

#1906 [ユーザ登録] メール埋め込みタグをカスタマイズできるように対応
  app/Enums/UserColumnType.php
  app/Models/Core/UsersColumns.php
  app/Plugins/Manage/UserManage/UsersTool.php
  resources/views/plugins/manage/user/description_frame_mails.blade.php
Labels: developer update

#1907 [コア] no_image画像追加
  public/images/core/no_image/no_image3.png
Labels: developer update

#1909 [コア] forbidden画像はキャッシュしない
  app/Http/Controllers/Core/UploadController.php
Labels: enhancement

#1910 [サイト管理] エラー設定画面にNo Image画像の設定追加
  app/Http/Controllers/Core/UploadController.php
  app/Plugins/Manage/SiteManage/SiteManage.php
  resources/views/plugins/manage/site/page_error.blade.php
Labels: new feature

#1911 [新着情報] プラグインを配置して新規作成＞登録後は設定変更に画面遷移させる等の対応
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
  resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_list_buckets.blade.php
  resources/views/plugins/user/whatsnews/whatsnews_frame_edit_tab.blade.php
Labels: enhancement

#1913 [新着情報] もっと見るボタン押下時に不要なリダイレクトの発生をなくす
  resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
Labels: bug

#1915 [コア] オプション管理プラグインの管理者メニュー自動対応
  resources/views/plugins/manage/menus.blade.php
  resources/views/plugins/manage/menus_list_option.blade.php
Labels: developer update

#1916 [ページ管理] 外部ページインポートで取り込み済み移行データがあると500エラー（File not found at path: migration/import/pages/1）になる不具合等対応
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/migration_order.blade.php
Labels: bug

#1917 [ページ管理] 外部ページインポートの取り込み済み移行データが削除できない不具合の変数名見直し
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/migration_order.blade.php
Labels: ignore for release

#1891 [テスト＆マニュアル]WYSIWYSテスト時のタイミング変更
  .gitignore
  tests/Browser/Common/WysiwygTest.php
  tests/Browser/screenshots/.gitignore
Labels: bug, ignore for release

#1919 [テスト] PageFactory追加
  app/Models/Common/Page.php
  database/factories/Common/PageFactory.php
Labels: developer update

#1920 [コア] ページ管理等で共通変数のtop_pageがセットされず毎回再取得していた不具合修正
  app/Http/Controllers/Core/ClassController.php
  app/Http/Kernel.php
Labels: bug

#1921 [ページ管理] パフォーマンス改善
  app/Models/Common/Page.php
  resources/views/plugins/manage/page/page.blade.php
Labels: enhancement

#1918 [コア] トークンの時間切れ（419エラー）時は自動で画面再表示（自動リダイレクト）
  app/Exceptions/Handler.php
  resources/views/common/flash_message_for_header.blade.php
  resources/views/core/cms.blade.php
  resources/views/core/cms_frame_header.blade.php
  resources/views/plugins/manage/manage.blade.php
Labels: enhancement

#1922 [CSVダウンロード] レスポンス版のCSVデータ整形処理をメソッド化
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/User/Counters/CountersPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Opacs/OpacsPlugin.php
  app/Utilities/Csv/CsvUtils.php
Labels: developer update

#1923 [フォーム] まとめ行を入れ子にするとエラーになる不具合対応
  resources/views/plugins/user/forms/default/forms.blade.php
  resources/views/plugins/user/forms/default/forms_confirm.blade.php
  resources/views/plugins/user/forms/default/include_error_multiple_group.blade.php
Labels: bug

#1924 [フォーム] まとめ行を入れ子にするとエラーになる不具合対応2
  resources/views/plugins/user/forms/default/forms.blade.php
Labels: ignore for release

#1925 [フォーム] まとめ行の必須チェックは一旦させない
  app/Plugins/User/Forms/FormsPlugin.php
Labels: bug

#1908 [コア]一般プラグインのJSONレスポンスアクションでPOSTも許可します
  routes/web.php
Labels: developer update

#1926 [ユーザ管理] CSVダウンロードで削除したカラムの値まで含まれる不具合対応
  app/Plugins/Manage/UserManage/UsersTool.php
Labels: bug
