Repository opensource-workshop/connect-cms, pull requests merged in 2023-03, with the labels that each got.

#1595 [メール送信] オプションプラグインに対応
  resources/views/plugins/common/frame_edit_mails.blade.php
Labels: enhancement

#1596 [エラーメッセージ] 入力チェックのinのエラーメッセージ内の選択肢を強調するように見直し
  resources/lang/ja/validation.php
Labels: enhancement

#1597 [連番管理] 連番クリア機能の無効化設定追加
  .env.example
  app/Models/Common/Numbers.php
  app/Plugins/Manage/NumberManage/NumberManage.php
  app/Plugins/PluginBase.php
  config/connect.php
  resources/views/plugins/manage/number/number.blade.php
Labels: enhancement

#1599 [データベース] 検索結果０件時にメッセージ出ない不具合修正（table, design-table-dlテンプレート）
  resources/views/plugins/user/databases/design-table-dl/databases.blade.php
  resources/views/plugins/user/databases/table/databases.blade.php
Labels: bug

#1598 [フォーム]新規登録の場合は「データ保存」はonにしておく対応を入れました。
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
Labels: enhancement

#1594 [サイト管理 - サイト設計書]サイト設計書の出力パフォーマンスUP対応＆機能強化
  app/Plugins/Manage/SiteManage/SiteManage.php
  resources/views/plugins/manage/site/document.blade.php
  resources/views/plugins/manage/site/pdf/api_list.blade.php
  resources/views/plugins/manage/site/pdf/auth_netcommons2.blade.php
  resources/views/plugins/manage/site/pdf/check_link.blade.php
Labels: bug

#1602 [ブログ] 一時保存のredirect_pathは保存時と同一のredirect_pathでよいため、セットできてないredirect_pathのJSセット指定行を削除
  resources/views/plugins/user/blogs/default/blogs_input.blade.php
Labels: bug

#1601 [テンプレート] 任意のエラーメッセージテンプレートをcommonに移動
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/common/error_messages.blade.php
Labels: developer update

#1605 [データベース] 項目設定で複数年月型に更新する時、キャプションが空だったらキャプションを自動設定する機能が動いていない不具合修正
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1607 [サイト管理]サイト設計書のリンク切れチェック出力で見出し名の平伏を合わせました
  app/Plugins/Manage/SiteManage/SiteManage.php
  resources/lang/en/messages.php
  resources/lang/ja/messages.php
  resources/views/plugins/manage/site/document.blade.php
  resources/views/plugins/manage/site/pdf/check_link.blade.php
Labels: bug

#1606 [タブ]共通エリアに配置された時、タブが表示されなくなるバグを修正しました。
  app/Plugins/User/Tabs/TabsPlugin.php
Labels: bug

#1608 [データベース] 数値チェック=ONにした後、選択肢型に切替て、登録時に選択肢未入力で確認画面に行くと500エラーになる不具合対応
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1580 [データベース]複数選択での絞り込み機能を追加しました
  app/Enums/DatabaseFrameConfig.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databases/DatabasesTool.php
  config/app.php
  database/migrations/2023_02_15_035825_add_use_select_and_or_flag_to_databases_columns_table.php
  resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
Labels: new feature

#1611 [エラー画面] バケツ未選択ワーニング画面をオプションプラグインにも対応
  resources/views/plugins/common/empty_bucket_setting.blade.php
Labels: developer update

#1613 [データベース] どこからも使ってないdatabase_checkbox.blade削除
  resources/views/plugins/user/databases/default/database_checkbox.blade.php
Labels: developer update

#1615 [データベース]初期表示オフの時に検索結果のページ番号を押すと検索結果が表示されない事象を修正しました
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1617 [役割設定] 定義名にダッシュ(-)、下線(_)も入力可能にする
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/plugins/manage/user/original_role.blade.php
Labels: enhancement

#1619 [Git] /app/Jobs/Options/*をgitから除外
  .gitignore
Labels: developer update

#1620 [メール送信] 非同期でConnectMailを送れるよう対応
  app/Jobs/ConnectMailJob.php
  app/Plugins/User/UserPluginBase.php
Labels: developer update

#1618 [ユーザ管理]ユーザー項目「所属型」を追加しました
  app/Enums/UserColumnType.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/RegistersUsers.php
  app/Models/Core/Section.php
  app/Models/Core/UserSection.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Manage/UserManage/UsersTool.php
  app/User.php
  database/migrations/2023_03_13_004114_create_sections_table.php
  database/migrations/2023_03_13_004115_create_user_sections_table.php
  resources/views/auth/registe_form_input_affiliation.blade.php
  resources/views/plugins/manage/user/edit_column_detail.blade.php
  resources/views/plugins/manage/user/edit_columns.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
  resources/views/plugins/manage/user/list_include_value.blade.php
  resources/views/plugins/manage/user/list_search_affiliation.blade.php
Labels: enhancement, manage(user)

#1622 [アップロードファイル管理] アップロードファイル一覧にサムネイル画像を追加しました
  app/Enums/ImageMimetype.php
  app/Models/Common/Uploads.php
  app/Models/User/Photoalbums/PhotoalbumContent.php
  resources/views/plugins/manage/uploadfile/index.blade.php
  resources/views/plugins/user/photoalbums/default/index_image.blade.php
Labels: enhancement

#1627 [データベース]絞り込み項目の登録済み件数を表示する機能を追加しました(beta)
  .env.example
  app/Models/User/Databases/DatabasesColumnsSelects.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  config/connect.php
Labels: plugin(database), developer update

#1626 [データベース]詳細画面で非表示項目をパラメータのID指定で強制的に表示する機能を追加しました(beta)
  .env.example
  app/Plugins/User/Databases/DatabasesPlugin.php
  config/connect.php
  resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
Labels: plugin(database), developer update

#1624 [NC3移行] 汎用DBのファイル型のファイルが全て同じファイルで移行される不具合の修正
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#1625 [データベース] DB選択でmysql5.6でエラーに対応（SQLSTATE[42000]: Syntax error or access violation: 1055 'cc_db.frames.bucket_id' isn't in GROUP BY）
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: bug

#1631 [コア]Install AWS SDK for PHP
  composer-dev.json
  composer-dev.lock
Labels: developer update
