Repository opensource-workshop/connect-cms, pull requests merged in 2023-08, with the labels that each got.

#1786 [フレーム] 利用者が見れるフレーム判定にログイン後非表示を対応
  app/Models/Common/Frame.php
Labels: bug

#1787 [フォトアルバム] 右・左エリア = スマホ表示と同等にする
  resources/views/plugins/user/photoalbums/card/index_folder.blade.php
  resources/views/plugins/user/photoalbums/default/bucket.blade.php
  resources/views/plugins/user/photoalbums/default/index_folder.blade.php
  resources/views/plugins/user/photoalbums/default/index_image.blade.php
Labels: bug

#1788 [robots.txt] 不要な検索botのクロールを除外
  public/robots.txt
Labels: enhancement

#1790 [DB初期データ] base_themeのcategory見直し
  database/seeders/DefaultConfigsTableSeeder.php
Labels: ignore for release

#1791 【NC3移行】NC3移行でのカウンター名出力箇所を修正しました
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, migration

#1793 [NC3移行]多言語サイトでの出力不具合を修正しました
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, migration

#1795 [フレーム] 非公開・限定公開・ログイン後非表示のプレビュー対応
  app/Models/Common/Frame.php
Labels: bug

#1796 [データベース]絞り込み項目の登録済み件数を表示する機能（beta）の処理を改善しました
  app/Plugins/User/Databases/DatabasesPlugin.php
Labels: plugin(database), developer update

#1797 [スライドショー] 高さ指定のレスポンシブ対応
  resources/views/plugins/user/slideshows/default/slideshows.blade.php
Labels: enhancement

#1798 [ユーザ情報] 項目毎に自動ユーザ登録時の表示指定、マイページの表示指定、マイページの編集指定を設定できるように対応
  app/Enums/EditType.php
  app/Enums/UserColumnType.php
  app/Enums/UserRegisterNoticeEmbeddedTag.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/RegistersUsers.php
  app/Http/Middleware/ConnectLog.php
  app/Models/Core/UsersColumns.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Manage/UserManage/UsersTool.php
  app/Plugins/Mypage/IndexMypage/IndexMypage.php
  app/Plugins/Mypage/LoginHistoryMypage/LoginHistoryMypage.php
  app/Plugins/Mypage/ProfileMypage/ProfileMypage.php
  app/Traits/Migration/MigrationTrait.php
  config/app.php
  database/migrations/2023_08_10_112746_add_fixed_column_name_display_edit_type_from_users_columns.php
  database/migrations/2023_08_10_114737_migration_fixed_column_from_users_columns.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DefaultUsersColumnsSetTableSeeder.php
  database/seeders/DefaultUsersColumnsTableSeeder.php
  resources/views/auth/registe_form.blade.php
  resources/views/plugins/manage/user/auto_regist.blade.php
  resources/views/plugins/manage/user/edit_column_detail.blade.php
  resources/views/plugins/manage/user/edit_columns.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
  resources/views/plugins/manage/user/list.blade.php
  resources/views/plugins/mypage/index/index.blade.php
  resources/views/plugins/mypage/profile/edit_form.blade.php
  tests/Browser/Manage/users.csv
Labels: new feature

#1794 [NC3移行]NC3フォトアルバム（スライドショー）対象取得クエリの修正
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, migration

#1801 [ユーザ登録] 任意項目のオプションテンプレート追加対応・ユーザ項目セット, 任意項目に変数名を登録できるよう対応
  .gitignore
  app/Enums/EnumsBase.php
  app/Enums/UserColumnType.php
  app/Models/Core/UsersColumns.php
  app/Models/Core/UsersColumnsSet.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Manage/UserManage/UsersTool.php
  database/migrations/2023_08_28_134821_add_use_variable_variable_name_from_users_columns_sets.php
  database/migrations/2023_08_28_135126_add_use_variable_variable_name_from_users_columns.php
  resources/views/auth/registe_form.blade.php
  resources/views/auth/registe_form_input_affiliation.blade.php
  resources/views/auth/registe_form_input_checkbox.blade.php
  resources/views/auth/registe_form_input_radio.blade.php
  resources/views/auth/registe_form_input_select.blade.php
  resources/views/plugins/manage/user/column_sets.blade.php
  resources/views/plugins/manage/user/edit_column_detail.blade.php
  resources/views/plugins/manage/user/edit_column_set.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
  resources/views/plugins/manage/user/list.blade.php
  resources/views/plugins/manage/user/list_search_text.blade.php
Labels: developer update

#1803 [ユーザ管理] ユーザ一覧検索で検索条件を開いたまま再表示できるオプション変数を追加, ユーザ一覧検索で検索条件を部分一致か完全一致かカラム型で設定できるオプションメソッドを追加
  app/Enums/UserColumnType.php
  app/Models/Core/UsersColumns.php
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/plugins/manage/user/list.blade.php
Labels: developer update

#1804 [NC3移行]長すぎるファイル名の場合には文字数を削除する
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug, migration

#1805 [GitHub action] Downgrade Chrome browser to v114
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: ignore for release

#1806 [フォーム] 登録一覧の編集画面で項目名と値が被って表示される不具合修正
  resources/views/plugins/user/forms/default/forms_edit_input.blade.php
Labels: bug

#1807 [ユーザ登録] 表示のみのカラム型, 自動登録のみ表示するカラム型 判定メソッド等追加
  app/Enums/UserColumnType.php
  app/Models/Core/UsersColumns.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Mypage/ProfileMypage/ProfileMypage.php
  resources/views/auth/registe_form.blade.php
  resources/views/plugins/manage/user/edit_column_detail.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
  resources/views/plugins/mypage/index/include_index_column_value.blade.php
  resources/views/plugins/mypage/index/index.blade.php
  resources/views/plugins/mypage/profile/edit_form.blade.php
Labels: developer update

#1810 [開館カレンダー]パターンデータが登録されていない場合にエラーの修正
  resources/views/plugins/user/openingcalendars/designbase/openingcalendars.blade.php
Labels: bug

#1811 [ユーザ管理] 項目設定で選択肢なしの時の「選択肢がありません。」メッセージが表示されない不具合修正、項目設定で設定した選択肢が一覧表示されない不具合修正
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/plugins/manage/user/edit_columns.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
Labels: bug

#1809 [新着情報]非同期で表示する機能を追加しました
  app/Enums/WhatsnewFrameConfig.php
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
  resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php
  resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
Labels: enhancement, plugin(whatsnews)

#1812 [コア]画像縮小表示時の回転不具合の修正
  app/Http/Controllers/Core/UploadController.php
Labels: bug
