Repository opensource-workshop/connect-cms, pull requests merged in 2024-06, with the labels that each got.

#2020 [パスワード付ページ] 末尾のページIDを消して表示すると500エラー対応
  routes/web.php
Labels: bug

#2021 [コア]使用ライブラリにSortableを追加しました
  package-lock.json
  package.json
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/js/bootstrap.js
Labels: developer update

#2017 [ログイン]ログイン・プラグインを作成しました。
  app/Http/Controllers/Auth/LoginController.php
  app/Models/User/Logins/Login.php
  app/Plugins/User/Logins/LoginsPlugin.php
  app/Plugins/User/Logins/plugin.ini
  database/migrations/2024_05_21_000000_create_logins_table.php
  resources/views/plugins/user/logins/default/bucket.blade.php
  resources/views/plugins/user/logins/default/login_buckets.blade.php
  resources/views/plugins/user/logins/default/logins.blade.php
  resources/views/plugins/user/logins/logins_frame_edit_tab.blade.php
  tests/Browser/Manage/PageManageTest.php
  tests/Browser/Manage/page.csv
  tests/Browser/User/LoginsPluginTest.php
  tests/bin/connect-cms-test.bat
Labels: additional request

#2026 [マニュアル＆テスト]Connect-Speechとフォームのマニュアル＆テスト・プログラムを追加しました。
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  tests/Browser/ConnectStudy/SpeechStudyTest.php
  tests/Browser/ConnectStudy/study_page.csv
  tests/Browser/User/FormsPluginTest.php
Labels: ignore for release

#2027 [テスト＆マニュアル]Connect-Studyのテストの微修正
  tests/Browser/ConnectStudy/ConnectStudyCommon.php
Labels: ignore for release

#2032 [単体テスト] Bucktes, FrameにFactory追加
  app/Models/Common/Buckets.php
  app/Models/Common/Frame.php
  database/factories/Common/BucketsFactory.php
  database/factories/Common/FrameFactory.php
Labels: developer update

#2034 [コア] Kernelに毎分実行用のオプションバッチスケジュール処理を追加
  app/Console/Kernel.php
Labels: new feature
