Repository opensource-workshop/connect-cms, pull requests merged in 2024-04, with the labels that each got.

#1990 [API] NC2からのSSOで自動ユーザ作成時に500エラー対応
  app/Plugins/Api/Nc2Sso/Nc2Sso.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Manage/UserManage/UsersTool.php
Labels: bug

#1991 [外部認証] 外部認証後のCCユーザ自動作成時に500エラー対応
  app/Http/Controllers/Auth/LoginController.php
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1989 [カウンター]ボット判定を追加
  app/Utilities/Request/RequestUtils.php
Labels: enhancement, additional request

#1995 [フォーム] CAPTCHAの注釈テキストに追記
  resources/views/plugins/user/forms/default/index_captcha.blade.php
Labels: enhancement

#1998 [フォーム] キャプチャのバリデーションメッセージ修正
  app/Plugins/User/Forms/FormsPlugin.php
Labels: enhancement

#1999 [フォーム] キャプチャのバリデーションメッセージ修正（langの方を修正するよう変更）
  app/Plugins/User/Forms/FormsPlugin.php
  resources/lang/en/validation.php
  resources/lang/ja/validation.php
Labels: enhancement

#2000 Change composer update php73
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/phpcs.yml
  composer-dev.lock
  composer.lock
Labels: developer update

#2001 [Docker] 設定値見直し
  docker-compose.yml
  docker/app/setup.sh
Labels: developer update

#2003 [github action] Update laravel_dusk_connect-cms-test-matrix.yml php7.3対応
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
Labels: ignore for release

#1993 [サイト管理, ページ管理] スマホメニュー機能のUI改善
  app/Enums/SmartphoneMenuTemplateType.php
  app/Plugins/Manage/SiteManage/SiteManage.php
  config/app.php
  database/migrations/2024_04_11_124942_initialize_smartphone_menu_defaults.php
  resources/views/layouts/app.blade.php
  resources/views/plugins/manage/page/page_form.blade.php
  resources/views/plugins/manage/site/pdf/base_main.blade.php
  resources/views/plugins/manage/site/site.blade.php
  tests/Browser/Manage/PageManageTest.php
Labels: enhancement

#2004 CSVダウンロードのヘッダー指定の大文字・小文字修正
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/User/Counters/CountersPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Forms/FormsPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Opacs/OpacsPlugin.php
Labels: developer update

#2005 composer update php73
  composer-dev.lock
  composer.lock
Labels: developer update

#2007 [コア] 初期データ投入seederでスマホメニュー表示形式を登録するよう修正
  database/migrations/2024_04_11_124942_initialize_smartphone_menu_defaults.php
  database/seeders/DefaultConfigsTableSeeder.php
Labels: bug
