Repository opensource-workshop/connect-cms, pull requests merged in 2024-11, with the labels that each got.

#2053 refactor: 不要なコードを削除（vueテンプレートコメントアウト部）
  resources/js/app.js
  resources/js/components/ExampleComponent.vue
  resources/js/components/ReservationsCalendarAddBooking.vue
Labels: リファクタリング, developer update

#2054 [ユーザ管理＞ユーザ変更] ラジオでON・OFF時、左側はOFFで統一する
  app/Enums/UserStatus.php
Labels: enhancement

#2055 [セキュリティ管理] ラジオでON・OFF時、左側はOFFで統一する
  app/Plugins/Manage/SecurityManage/SecurityManage.php
  resources/views/plugins/manage/security/loginpermit.blade.php
  resources/views/plugins/manage/security/purifier.blade.php
Labels: enhancement

#2058 [Composer] delete phpoffice/phpspreadsheet from composer-dev.json
  composer-dev.json
  composer-dev.lock
Labels: developer update

#2059 [Github actions] laravel_dusk_connect-cms-test-matrixのデイリー実行版を追加
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml
  .github/workflows/laravel_dusk_daily.yml
Labels: developer update

#2062 [プラグイン設定] 権限設定のリダイレクト対応 & 更新時にメッセージ表示
  app/Plugins/User/UserPluginBase.php
  resources/views/plugins/common/frame_edit_buckets.blade.php
  resources/views/plugins/common/frame_edit_roles.blade.php
Labels: enhancement

#2063 [アップロードファイル] ダウンロード数が全ての拡張子でカウントされるように修正
  app/Http/Controllers/Core/UploadController.php
  config/connect.php
Labels: bug

#2068 [サイト内検索] 多言語モード採用時、対象言語ページの絞り込みが効かないバグを修正
  app/Plugins/User/Bbses/BbsesPlugin.php
  app/Plugins/User/Faqs/FaqsPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
Labels: bug

#2070 [データベース] 項目設定＞項目詳細設定＞DBカラム設定, ラジオでON・OFF時、左側はOFFで統一する
  resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
Labels: enhancement

#2071 [グループ管理] 初期参加グループフラグ追加
  app/Http/Controllers/Auth/RegistersUsers.php
  app/Models/Common/Group.php
  app/Plugins/Manage/GroupManage/GroupManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  database/migrations/2024_11_19_132155_add_initial_group_flag_from_groups.php
  resources/views/plugins/manage/group/edit.blade.php
  resources/views/plugins/manage/group/index.blade.php
  resources/views/plugins/manage/group/list.blade.php
Labels: new feature

#2072 [テスト] GroupManageTest, グループ登録時のテスト修正
  tests/Browser/Manage/GroupManageTest.php
Labels: developer update

#2073 [プラグイン共通] フレーム編集のラジオでON・OFF時、左側はOFFで統一する
  app/Enums/ContentOpenType.php
  resources/views/core/cms_frame_edit.blade.php
Labels: enhancement

#2078 [PHP8.2] Using ${var} in strings is deprecated fix
  resources/views/plugins/user/databases/default/databases_edit_database.blade.php
  resources/views/plugins/user/photoalbums/default/frame.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_slideshow.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php
Labels: enhancement
