Repository opensource-workshop/connect-cms, pull requests merged in 2024-02, with the labels that each got.

#1951 [wysiwyg] インストール時「初期に選択させる画像サイズ」を小に変更
  app/Enums/ResizedImageSize.php
  resources/views/plugins/manage/site/pdf/base_wysiwyg.blade.php
Labels: enhancement

#1942 【WYSIWIG】ディレクトリインストール時のcontent_css:のパス修正
  resources/views/plugins/common/wysiwyg.blade.php
Labels: bug

#1937 【RSS】プラグイン作成
  app/Enums/PluginName.php
  app/Models/User/Rsses/RssUrls.php
  app/Models/User/Rsses/Rsses.php
  app/Plugins/User/Rsses/RssesPlugin.php
  app/Plugins/User/Rsses/plugin.ini
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  database/migrations/2023_12_18_140036_create_rsses_table.php
  database/migrations/2023_12_18_140041_create_rss_urls_table.php
  resources/views/plugins/user/rsses/default/rsses.blade.php
  resources/views/plugins/user/rsses/default/rsses_edit.blade.php
  resources/views/plugins/user/rsses/default/rsses_edit_row.blade.php
  resources/views/plugins/user/rsses/default/rsses_edit_row_add.blade.php
  resources/views/plugins/user/rsses/default/rsses_edit_rss.blade.php
  resources/views/plugins/user/rsses/default/rsses_error_messages.blade.php
  resources/views/plugins/user/rsses/default/rsses_list_buckets.blade.php
  resources/views/plugins/user/rsses/default/template.ini
  resources/views/plugins/user/rsses/rsses_frame_edit_tab.blade.php
  tests/Browser/User/RssesPluginTest.php
Labels: additional request

#1953 [Utils] setlocale()のwin & linux対応
  app/Models/Common/Uploads.php
  app/Plugins/Manage/CodeManage/CodeManage.php
  app/Plugins/Manage/PageManage/PageManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/User/Calendars/CalendarsPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Utilities/Csv/CsvUtils.php
  app/Utilities/File/FileUtils.php
  resources/views/plugins/user/learningtasks/default/learningtasks_import_examinations.blade.php
Labels: developer update

#1954 [スライドショー]初期表示の速度を改善しました
  resources/views/plugins/user/slideshows/default/slideshows.blade.php
Labels: enhancement

#1956 [github action] 警告メッセージ対応（Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20）
  .github/workflows/laravel_dusk.yml
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
  .github/workflows/laravel_dusk_daily.yml
  .github/workflows/phpcs.yml
  .github/workflows/wiki.yml
Labels: developer update

#1957 [phpunit] Warning:Your XML configuration validates against a deprecated schema.対応
  phpunit.xml
Labels: developer update

#1958 [コア]オプションプラグインのCSSファイル読み込みを追加しました
  public/css/option/.gitignore
  resources/views/layouts/app.blade.php
Labels: developer update

#1959 [プラグイン全般]プラグインの設定アイコンで開く画面をフレーム編集に統一しました。
  app/Plugins/User/Bbses/BbsesPlugin.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  app/Plugins/User/Cabinets/CabinetsPlugin.php
  app/Plugins/User/Calendars/CalendarsPlugin.php
  app/Plugins/User/Contents/ContentsPlugin.php
  app/Plugins/User/Conventions/ConventionsPlugin.php
  app/Plugins/User/Counters/CountersPlugin.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
  app/Plugins/User/Faqs/FaqsPlugin.php
  app/Plugins/User/Forms/FormsPlugin.php
  app/Plugins/User/Knowledges/KnowledgesPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Linklists/LinklistsPlugin.php
  app/Plugins/User/Menus/MenusPlugin.php
  app/Plugins/User/Opacs/OpacsPlugin.php
  app/Plugins/User/Openingcalendars/OpeningcalendarsPlugin.php
  app/Plugins/User/Photoalbums/PhotoalbumsPlugin.php
  app/Plugins/User/Reservations/ReservationsPlugin.php
  app/Plugins/User/Rsses/RssesPlugin.php
  app/Plugins/User/Searchs/SearchsPlugin.php
  app/Plugins/User/Slideshows/SlideshowsPlugin.php
  app/Plugins/User/Tabs/TabsPlugin.php
  app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
Labels: enhancement

#1962 [WYSIWYG]画像ダイアログの詳細タブで保存すると画像がリサイズされない問題を修正しました
  public/js/tinymce/plugins/image/plugin.min.js
  resources/views/plugins/common/wysiwyg.blade.php
Labels: bug

#1960 [RSS]左右用のテンプレートを追加しました
  resources/views/plugins/user/rsses/side/rsses.blade.php
  resources/views/plugins/user/rsses/side/template.ini
Labels: enhancement
