Repository opensource-workshop/connect-cms, pull requests merged in 2024-01, with the labels that each got.

#1927 [移行ツール] Nc2Authorityモデル追加
  app/Models/Migration/Nc2/Nc2Authority.php
Labels: developer update

#1928 [フレーム設定] body class名設定追加
  app/Http/Controllers/Core/FrameCore.php
  app/Models/Common/Frame.php
  database/migrations/2024_01_07_114703_add_classname_body_from_frames.php
  resources/views/core/cms_frame_base.blade.php
  resources/views/core/cms_frame_edit.blade.php
  resources/views/core/cms_frame_header.blade.php
Labels: enhancement

#1930 [DB] users_input_colsテーブルにインデックス追加
  database/migrations/2024_01_10_100428_add_users_id_and_users_columns_id_index_from_users_input_cols.php
Labels: developer update

#1931 [移行ツール] インポートコマンド実行時、redoオプション未設定でもtargetのデータが消える不具合修正
  app/Traits/Migration/MigrationTrait.php
Labels: bug

#1932 [ブログ] 投稿者絞込用リストに全投稿者がリスト表示されない場合がある不具合対応
  app/Plugins/User/Blogs/BlogsPlugin.php
Labels: bug

#1935 [OPAC] 書籍データ取得で国会図書館APIのURLが変わったことによる500エラー対応
  app/Plugins/User/Opacs/OpacsPlugin.php
  app/Utilities/Curl/CurlUtils.php
Labels: bug

#1938 [ユーザ管理] 承認完了メールが飛ばない不具合対応
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/plugins/manage/user/auto_regist.blade.php
Labels: bug

#1929 【オプション】オプション・プラグインのJavaScriptライブラリのディレクトリをGitignoreに指定しました。
  .gitignore
Labels: core

#1944 [ユーザ管理] 承認完了メールの埋め込みタグに本登録メールと同じものを実装
  app/Plugins/Manage/UserManage/UserManage.php
  resources/views/plugins/manage/user/auto_regist.blade.php
Labels: enhancement

#1947 [ページ管理] 一番上へ・一番下へボタン追加
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/page.blade.php
  resources/views/plugins/manage/user/list.blade.php
Labels: new feature

#1948 [パスワードリセット] 新しいパスワードの項目名をプロフィール変更と同じに見直し
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
Labels: enhancement

#1949 [ブログ] 記事登録の重要記事・カテゴリにcssクラス追加
  resources/views/plugins/user/blogs/default/blogs_input.blade.php
Labels: developer update
