Repository opensource-workshop/connect-cms, pull requests merged in 2024-03, with the labels that each got.

#1966 [ユーザ管理]インポートの新規登録でシステムエラーとなる問題を修正しました
  app/Plugins/Manage/UserManage/UserManage.php
Labels: bug

#1968 [カレンダー] 同一日内の予定を時間順に表示
  app/Plugins/User/Calendars/CalendarsPlugin.php
Labels: enhancement

#1970 [マイページ] コンテンツ画面へ→トップページへ表示に見直し
  resources/views/layouts/app.blade.php
Labels: enhancement

#1972 [マイページ] マイページトップページとプロフィールページの画面名変更
  resources/views/plugins/mypage/index/index.blade.php
  resources/views/plugins/mypage/menus_list.blade.php
  resources/views/plugins/mypage/profile/profile_mypage_tab.blade.php
Labels: enhancement

#1974 [ユーザ管理] ユーザ一覧表示時にユーザ項目の複数選択肢がnull時のphp8対応
  resources/views/plugins/manage/user/list_include_value.blade.php
Labels: bug

#1975 [ページ管理] ページ変更画面のクラス名の名称変更
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/page_form.blade.php
Labels: enhancement

#1967 [データベース]閲覧者による表示件数の変更機能を追加しました
  app/Enums/DatabaseFrameConfig.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  resources/views/plugins/user/databases/default/databases.blade.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/databases/default/databases_include_page_total_views.blade.php
  resources/views/plugins/user/databases/default/databases_include_view_count.blade.php
  resources/views/plugins/user/databases/design-table-dl/databases.blade.php
Labels: plugin(database), new feature

#1979 composer require mews/captcha for php8.0
  composer-dev.lock
  composer.lock
Labels: developer update

#1980 [RSSプラグイン] RSSプラグインのマニュアル対応をしました。
  app/Plugins/User/Rsses/RssesPlugin.php
  tests/Browser/Manage/page.csv
  tests/Browser/User/RssesPluginTest.php
  tests/Manual/insertion/user/function_foot.txt
  tests/Manual/insertion/user/function_foot_pdf.txt
  tests/bin/connect-cms-test.bat
Labels: ignore for release

#1981 [ページマネージャー・テスト] RSSプラグインの修正漏れ対応です。
  tests/Browser/Manage/PageManageTest.php
Labels: bug, ignore for release

#1983 [github action] RSSテスト追加
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: developer update

#1985 [composer] captchaライブラリのphp8.0対応のバージョン指定
  composer-dev.json
  composer-dev.lock
  composer.json
  composer.lock
Labels: bug

#1988 [フォーム] 登録時のリダイレクト対応
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/user/forms/default/forms.blade.php
  resources/views/plugins/user/forms/default/forms_confirm.blade.php
  resources/views/plugins/user/forms/default/forms_confirm_tandem.blade.php
  resources/views/plugins/user/forms/default/forms_confirm_token.blade.php
Labels: enhancement
