Repository opensource-workshop/connect-cms, pull requests merged in 2024-05, with the labels that each got.

#2009 [マニュアル]WYSIWYGのエラー時の説明追加と開発版へのphpofficeを追加
  composer-dev.json
  composer-dev.lock
  tests/Browser/Common/WysiwygTest.php
  tests/Manual/insertion/common/wysiwyg/error/foot.txt
Labels: ignore for release

#2012 [ログ管理]インストール時に初期値で取得するログの設定を追加しました。
  database/seeders/DefaultConfigsTableSeeder.php
Labels: enhancement

#2014 [施設予約] 施設予約の各施設へ（今月）リンク機能を追加
  app/Plugins/User/Reservations/ReservationsPlugin.php
Labels: enhancement

#2016 [テスト＆マニュアル]Windowsでテストする際のバッチにConnect-Studyのマイグレーションを設定しました。
  tests/bin/connect-cms-test.bat
Labels: bug, ignore for release

#2018 [スライドショー] アップロード管理等でファイル削除時、スライドショー管理画面でレコードが表示されなくなるのを修正
  app/Plugins/User/Slideshows/SlideshowsPlugin.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
Labels: bug

#2011 [カレンダー]開始日時・終了日時の初期値を利用しやすい時刻にしました
  app/Plugins/User/Calendars/CalendarsPlugin.php
Labels: enhancement, plugin(calendar)
