Repository opensource-workshop/connect-cms, pull requests merged in 2024-12, with the labels that each got.

#2079 [フレーム編集] 公開日時From、Toが限定公開以外でも入力できる不具合修正
  resources/views/core/cms_frame_edit.blade.php
Labels: bug

#2080 [施設管理] 予約一覧の絞込条件に利用日を追加 OW-2441
  app/Plugins/Manage/ReservationManage/ReservationManage.php
  resources/views/plugins/manage/reservation/bookings.blade.php
Labels: enhancement

#2083 [FAQ] 投稿日時が同値の場合、前へ／次へボタンで同値の投稿が飛ばされて表示される
  app/Plugins/User/Faqs/FaqsPlugin.php
Labels: bug

#2084 [開発ツール] オプションリポジトリ ←→ 開発環境のコピーサンプルShellにComposer Optionを追加
  dev_2_option_private.ps1.example
  option_private_2_dev.ps1.example
  sync_dev_2_option_private.sh.example
  sync_option_private_2_dev.sh.example
Labels: developer update

#2087 [Trait] ConnectRoleTrait::choiceUserRolesOrPageRoles()で$user->user_rolesがnullの場合の再取得する処理を追加
  app/Traits/ConnectRoleTrait.php
Labels: developer update

#2088 [GitHub Actions] DuskテストのInvalid path to Chromedriver対応
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: developer update

#2089 [GitHub Actions] Connect 1.x系のDuskテストのChrome failed to start: crashed. 対応
  .github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
Labels: developer update

#2090 [ブログ] 最後の記事だけクラス属性が付与されない不具合修正
  resources/views/plugins/user/blogs/default/blogs.blade.php
Labels: enhancement

#2091 [ブログ] 記事の中に → (&rarr;) があると「RSS2.0」アイコンをクリック時にエラーになる不具合対応
  app/Plugins/User/Blogs/BlogsPlugin.php
  app/Utilities/String/StringUtils.php
Labels: bug
