Repository opensource-workshop/connect-cms, pull requests merged in 2025-09, with the labels that each got.

#2258 [E2Eテスト] 安定化対応（ChromeDriver起動整理・スクショ修正・CIフラグ適用・脆弱テスト修正）
  .github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml
  .github/workflows/laravel_dusk_connect-cms-test-matrix.yml
  .github/workflows/laravel_dusk_connect-cms-test.yml
  tests/Browser/Manage/SiteManageTest.php
  tests/Browser/User/FaqsPluginTest.php
  tests/Browser/User/PhotoalbumsPluginTest.php
  tests/DuskTestCase.php
Labels: developer update

#2259 [GitHub Actions] リリース作成自動化とテストリトライ機能を追加しました
  .github/workflows/create-release-v1-v2.yml
  .github/workflows/test-v2.yml
Labels: developer update

#2261 [フォーム] 本登録後のメッセージを必須項目に設定しました
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
Labels: enhancement

#2263 [キャビネット] フォルダ間の移動機能を追加しました
  app/Plugins/User/Cabinets/CabinetsPlugin.php
  app/Rules/CabinetNoDuplicateNameInDestination.php
  app/Rules/CabinetNotIntoDescendant.php
  app/Rules/CabinetSameCabinet.php
  app/Rules/CabinetValidDestinationFolder.php
  resources/views/plugins/user/cabinets/default/folder_options.blade.php
  resources/views/plugins/user/cabinets/default/index.blade.php
  tests/Feature/Plugins/User/Cabinets/CabinetMoveFeatureTest.php
  tests/Unit/Plugins/User/Cabinets/CabinetMoveValidationTest.php
Labels: plugin(cabinet), new feature

#2265 [GitHub Actions] v2リリース時のPR作成と競合解決処理を改善しました
  .github/workflows/create-release-v1-v2.yml
Labels: developer update

#2266 [コア] 例外レンダリング時のnull参照を防止しました
  app/Models/Core/Configs.php
Labels: developer update

#2276 [メニュー] モデレータがメニューを編集できるようにしました
  app/Enums/MenuFrameConfig.php
  app/Plugins/User/Menus/MenusPlugin.php
  config/app.php
  resources/views/plugins/user/menus/ancestor_descendant_sibling/menus.blade.php
  resources/views/plugins/user/menus/breadcrumbs/menus.blade.php
  resources/views/plugins/user/menus/common/edit_button.blade.php
  resources/views/plugins/user/menus/default/menus.blade.php
  resources/views/plugins/user/menus/default/menus_edit_roles.blade.php
  resources/views/plugins/user/menus/default/menus_select.blade.php
  resources/views/plugins/user/menus/dropdown/menus.blade.php
  resources/views/plugins/user/menus/dropdown_hamburger/menus.blade.php
  resources/views/plugins/user/menus/footersitemap/menus.blade.php
  resources/views/plugins/user/menus/footersitemap_no_rootrink/menus.blade.php
  resources/views/plugins/user/menus/hamburger/menus.blade.php
  resources/views/plugins/user/menus/hamburger_button/menus.blade.php
  resources/views/plugins/user/menus/menus_frame_edit_tab.blade.php
  resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php
  resources/views/plugins/user/menus/mouseover_dropdown_hamburger/menus.blade.php
  resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php
  resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menus.blade.php
  resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menus.blade.php
  resources/views/plugins/user/menus/opencurrenttree/menus.blade.php
  resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php
  resources/views/plugins/user/menus/parentsandchild/menus.blade.php
  resources/views/plugins/user/menus/sitemap/menus.blade.php
  resources/views/plugins/user/menus/sitemap_no_rootlink/menus.blade.php
  resources/views/plugins/user/menus/tab/menus.blade.php
  resources/views/plugins/user/menus/tab_flat/menus.blade.php
  tests/Feature/Plugins/User/Menus/MenusModeratorEditFeatureTest.php
Labels: enhancement, plugin(menu)

#2278 [システム] Option Plugins用設定ファイルをgitignoreに追加しました
  config/.gitignore
Labels: ignore for release, developer update

#2280 [フレーム] 公開設定のラジオボタン選択状態が正しく表示されない不具合を修正しました
  resources/views/core/cms_frame_edit.blade.php
Labels: bug
