Repository opensource-workshop/connect-cms, pull requests merged in 2025-07, with the labels that each got.

#2219 [WYSIWYG] TinyMCEのiframe埋め込みセキュリティ設定を追加しました
  resources/views/plugins/common/wysiwyg.blade.php
Labels: enhancement

#2222 [認証]全ユーザの強制ログアウト機能を作りました。
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Kernel.php
  app/Http/Middleware/ForceLogoutMiddleware.php
  app/Plugins/Manage/UserManage/UserManage.php
  database/migrations/2025_07_03_093934_add_force_logout_to_users_table.php
  resources/views/plugins/manage/user/force_logout.blade.php
  resources/views/plugins/manage/user/user_manage_tab.blade.php
Labels: new feature

#2208 [テーマ管理] ディレクトリ名のバリデーション不備による文字化けや重複の問題を修正しました
  app/Plugins/Manage/ThemeManage/ThemeManage.php
Labels: bug, mange(theme)

#2209 [RSS]XMLパースエラー発生時にシステムエラーとなる問題を修正しました
  app/Plugins/User/Rsses/RssesPlugin.php
  resources/views/plugins/user/rsses/default/rsses_error_messages.blade.php
Labels: bug, plugin(rsses)

#2225 [プラグイン共通] 投稿通知の件名が未設定の場合に500エラーが発生する問題を修正しました
  app/Models/Common/BucketsMail.php
  app/Plugins/User/UserPluginBase.php
  resources/views/plugins/common/frame_edit_mails.blade.php
  tests/Unit/Models/Common/BucketsMailTest.php
Labels: bug

#2226 [プラグイン共通] [サイト管理] カテゴリ設定でクラス名のバリデーション機能を追加しました
  app/Models/Common/Categories.php
  app/Plugins/Manage/SiteManage/SiteManage.php
  app/Rules/CustomValiUniqueClassname.php
  resources/views/plugins/common/description_plugin_category.blade.php
  resources/views/plugins/common/user_list_category.blade.php
  resources/views/plugins/manage/site/categories.blade.php
Labels: enhancement

#2227 [カテゴリ] カテゴリ設定にカラーピッカー機能を追加しました
  resources/views/plugins/common/description_plugin_category.blade.php
  resources/views/plugins/common/user_list_category.blade.php
  resources/views/plugins/manage/page/page_form.blade.php
  resources/views/plugins/manage/site/categories.blade.php
  resources/views/plugins/manage/site/site.blade.php
Labels: enhancement

#2231 [FAQ] Q&A全表示テンプレートを追加しました
  resources/views/plugins/user/faqs/full_display/faq_item.blade.php
  resources/views/plugins/user/faqs/full_display/faqs.blade.php
  resources/views/plugins/user/faqs/full_display/template.ini
Labels: new feature

#2232 [FAQ] キーワード検索機能を追加しました
  app/Enums/FaqFrameConfig.php
  app/Plugins/User/Faqs/FaqsPlugin.php
  resources/views/plugins/user/faqs/category/faqs.blade.php
  resources/views/plugins/user/faqs/clear_conditions.blade.php
  resources/views/plugins/user/faqs/count_display.blade.php
  resources/views/plugins/user/faqs/default/faqs.blade.php
  resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php
  resources/views/plugins/user/faqs/full_display/faqs.blade.php
  resources/views/plugins/user/faqs/search_form.blade.php
Labels: new feature

#2233 [メール] PHP7系でメール通知設定のUnion型エラーを修正しました
  app/Models/Common/BucketsMail.php
Labels: bug

#2235 [NC3移行] 多言語ページで日本語ページを優先して登録するよう修正しました
  app/Traits/Migration/MigrationNc3ExportTrait.php
Labels: bug

#2236 [共通] form-dataパッケージのセキュリティ脆弱性を修正しました
  package-lock.json
  package.json
Labels: developer update
