Repository opensource-workshop/connect-cms, pull requests merged in 2025-05, with the labels that each got.

#2187 [JSライブラリ][WYSIWYG] TinyMCEを5の最新版へアップデート OW-2523
  package-lock.json
  package.json
  public/js/app.js
  public/js/skins/ui/oxide/content.min.css
  public/js/skins/ui/oxide/skin.min.css
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/js/tinymce/plugins/image/plugin.js
  resources/views/plugins/common/wysiwyg.blade.php
  webpack.mix.js
Labels: developer update

#2188 [JSライブラリ][WYSIWYG] TinyMCEを5→6へアップデート OW-2523
  package-lock.json
  package.json
  public/js/app.js
  public/js/skins/ui/oxide/content.min.css
  public/js/skins/ui/oxide/skin.min.css
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/js/tinymce/langs/README.md
  resources/js/tinymce/langs/ja.js
  resources/js/tinymce/plugins/face/plugin.js
  resources/js/tinymce/plugins/file/plugin.js
  resources/js/tinymce/plugins/image/plugin.js
  resources/js/tinymce/plugins/pdf/plugin.js
  resources/js/tinymce/plugins/translate/plugin.js
  resources/views/plugins/common/wysiwyg.blade.php
  tests/Browser/Common/AdminLinkTest.php
  tests/Browser/User/ContentsPluginTest.php
  tests/Browser/User/FormsPluginTest.php
  webpack.mix.js
Labels: enhancement

#2190 [JSライブラリ][WYSIWYG][テーマ管理] TinyMCEを6→7へアップデート OW-2523
  app/Plugins/Manage/ThemeManage/ThemeManage.php
  package-lock.json
  package.json
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/js/tinymce/langs/ja.js
  resources/js/tinymce/plugins/image/plugin.js
  resources/views/plugins/common/wysiwyg.blade.php
  resources/views/plugins/manage/theme/theme.blade.php
  resources/views/plugins/manage/theme/theme_manage_tab.blade.php
Labels: developer update

#2193 [マイグレーション] DB::raw("select version() as version")の修正
  database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
Labels: developer update

#2194 [モデル] モデルの$dates → $castsに切替（Laravel10.xで$date廃止に対応）
  app/Models/Common/Frame.php
  app/Models/Common/Group.php
  app/Models/Common/GroupUser.php
  app/Models/Common/PageRole.php
  app/Models/Core/UsersLoginHistories.php
  app/Models/Migration/Nc3/Nc3Announcement.php
  app/Models/Migration/Nc3/Nc3AuthorizationKey.php
  app/Models/Migration/Nc3/Nc3Frame.php
  app/Models/User/Blogs/BlogsPosts.php
  app/Models/User/Blogs/BlogsPostsTags.php
  app/Models/User/Calendars/CalendarPost.php
  app/Models/User/Contents/Contents.php
  app/Models/User/Counters/CounterCount.php
  app/Models/User/Databases/DatabasesInputs.php
  app/Models/User/Faqs/FaqsPosts.php
  app/Models/User/Faqs/FaqsPostsTags.php
  app/Models/User/Forms/Forms.php
  app/Models/User/Learningtasks/LearningtasksExaminations.php
  app/Models/User/Learningtasks/LearningtasksPosts.php
  app/Models/User/Learningtasks/LearningtasksPostsFiles.php
  app/Models/User/Learningtasks/LearningtasksUseSettings.php
  app/Models/User/Opacs/OpacsBooks.php
  app/Models/User/Opacs/OpacsBooksLents.php
  app/Models/User/Reservations/ReservationsInput.php
  app/User.php
Labels: enhancement

#2195 [ブラウザテスト] .envからDUSK_DRIVER_URLを取得できるよう修正
  .env.example
  tests/DuskTestCase.php
Labels: developer update

#2196 [ブラウザテスト] .envからDUSK_NO_MANUAL_ALL／DUSK_NO_API_TEST_ALLを設定できるように対応
  .env.example
  tests/DuskTestCase.php
Labels: developer update

#2199 [TinyMCE] [テーマ管理：テンプレート編集] カスタムプラグイン「テンプレートの挿入」追加＆テーマ管理のテンプレート登録機能を復活
  app/Plugins/Manage/ThemeManage/ThemeManage.php
  public/js/app.js
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/js/tinymce/plugins/cc_template/plugin.js
  resources/views/plugins/common/wysiwyg.blade.php
  resources/views/plugins/manage/theme/theme.blade.php
  resources/views/plugins/manage/theme/theme_manage_tab.blade.php
  resources/views/plugins/manage/theme/theme_template_edit.blade.php
Labels: new feature

#2201 [ユーザ管理] ユーザ管理＞項目設定, 一覧のレイアウトが崩れるケースがある不具合（HTML有りのキャプション時）に対応
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
Labels: bug

#2203 [アップロードファイル][ユーザ管理] 一覧のページャ指定が、別ページ遷移後でも残っている不具合対応
  resources/views/plugins/manage/menus_list.blade.php
  resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php
  resources/views/plugins/manage/user/user_manage_tab.blade.php
Labels: bug

#2202 [施設予約] 「重複予約を許可しない」設定にしていても、予約の終了時間を「24:00」にすると重複して予約ができてしまう不具合対応
  app/Rules/CustomValiDuplicateBookings.php
Labels: bug
