Repository opensource-workshop/connect-cms, pull requests merged in 2025-04, with the labels that each got.

#2152 [日付入力] 日付入力ライブラリを tempusdominus-bootstrap-4 → @eonasdan/tempus-dominus v6に切替 OW-2520
  package-lock.json
  package.json
  public/css/app.css
  public/css/connect.css
  public/js/707.js
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/sass/app.scss
  resources/views/core/cms_frame_edit.blade.php
  resources/views/layouts/app.blade.php
  resources/views/plugins/common/datetimepicker.blade.php
  resources/views/plugins/manage/holiday/edit.blade.php
  resources/views/plugins/manage/log/log.blade.php
  resources/views/plugins/manage/reservation/bookings.blade.php
  resources/views/plugins/manage/reservation/edit.blade.php
  resources/views/plugins/user/blogs/default/blogs_input.blade.php
  resources/views/plugins/user/blogs/default/blogs_list_categories.blade.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/calendars/default/edit.blade.php
  resources/views/plugins/user/databases/default/databases_input.blade.php
  resources/views/plugins/user/databases/default/databases_input_date.blade.php
  resources/views/plugins/user/databases/default/databases_input_time.blade.php
  resources/views/plugins/user/faqs/default/faqs_input.blade.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  resources/views/plugins/user/forms/default/forms_input_date.blade.php
  resources/views/plugins/user/forms/default/forms_input_file.blade.php
  resources/views/plugins/user/forms/default/forms_input_mail.blade.php
  resources/views/plugins/user/forms/default/forms_input_text.blade.php
  resources/views/plugins/user/forms/default/forms_input_textarea.blade.php
  resources/views/plugins/user/forms/default/forms_input_time.blade.php
  resources/views/plugins/user/forms/default/forms_input_time_from_to.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_examinations.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_report.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks_edit_learningtasks.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks_input.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks_list_buckets.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks_list_categories.blade.php
  resources/views/plugins/user/learningtasks/old/learningtasks_show.blade.php
  resources/views/plugins/user/opacs/default/opacs.blade.php
  resources/views/plugins/user/opacs/default/opacs_input.blade.php
  resources/views/plugins/user/opacs/default/opacs_lent.blade.php
  resources/views/plugins/user/opacs/default/opacs_lentlist.blade.php
  resources/views/plugins/user/opacs/default/opacs_role_lent.blade.php
  resources/views/plugins/user/reservations/default/edit_booking.blade.php
Labels: developer update

#2154 [日付入力] datetimepicker.bladeに date オプション追加
  resources/views/plugins/common/datetimepicker.blade.php
Labels: developer update

#2156 [JSライブラリ] 前の日付入力で使われていたmoment.js除去 OW-2549
  package-lock.json
  package.json
  public/js/707.js
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/sass/tempusdominus-bootstrap-4-build.scss
  resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php
  resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
Labels: developer update

#2157 [ドキュメント] README.md にインストール、アップデート方法のリンク追加
  README.md
Labels: developer update

#2158 [Github Issues] issue登録時にフリー入力とBlank Issueがどちらも表示されている
  .github/ISSUE_TEMPLATE/config.yml
Labels: developer update

#2159 [メール通知] 削除通知が送信先グループに通知されない不具合修正
  app/Jobs/DeleteNoticeJob.php
Labels: bug

#2160 [メール通知] 送信メールアドレスなしの場合、ログ管理にログ登録するように対応
  app/Jobs/ApprovalNoticeJob.php
  app/Jobs/ApprovedNoticeJob.php
  app/Jobs/DeleteNoticeJob.php
  app/Jobs/PostNoticeJob.php
  resources/views/plugins/manage/log/log.blade.php
Labels: enhancement

#2161 [コードスタディ][JSライブラリ] CodeMirrorを直置きからnpmでインストールする形式に切替 OW-2552
  app/Plugins/User/Codestudies/CodestudiesPlugin.php
  package-lock.json
  package.json
  public/codemirror/lib/codemirror.css
  public/codemirror/lib/codemirror.js
  public/codemirror/lib/codemirror_cc.css
  public/codemirror/mode/clike/clike.js
  public/codemirror/mode/fortran/fortran.js
  public/codemirror/mode/javascript/javascript.js
  public/codemirror/mode/php/php.js
  public/codemirror/mode/python/python.js
  public/css/app.css
  public/css/connect.css
  public/js/app.js
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/sass/app.scss
  resources/views/plugins/user/codestudies/default/codestudies.blade.php
Labels: developer update

#2163 [テーマ管理][コードスタディ] テーマ管理＞編集画面にCodeMirror適用, コードスタディ＞javaのコード色適用に対応
  public/css/connect.css
  public/js/app.js
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/views/plugins/common/codemirror.blade.php
  resources/views/plugins/manage/theme/theme_css_edit.blade.php
  resources/views/plugins/manage/theme/theme_js_edit.blade.php
  resources/views/plugins/manage/theme/theme_template_edit.blade.php
  resources/views/plugins/user/codestudies/default/codestudies.blade.php
Labels: enhancement

#2164 [テーマ管理] テンプレート編集時、上部に画面名を表示するよう対応
  resources/views/plugins/manage/theme/theme_manage_tab.blade.php
Labels: bug

#2155 [課題管理]レポート提出状況をCSVで出力する機能を追加しました
  app/Models/Common/PageRole.php
  app/Models/Core/UsersRoles.php
  app/Models/User/Learningtasks/Learningtasks.php
  app/Models/User/Learningtasks/LearningtasksPosts.php
  app/Models/User/Learningtasks/LearningtasksUseSettings.php
  app/Models/User/Learningtasks/LearningtasksUsers.php
  app/Models/User/Learningtasks/LearningtasksUsersStatuses.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksReportCsvExporter.php
  app/Traits/Learningtasks/LearningtaskPostTrait.php
  app/Utilities/File/FileUtils.php
  database/factories/Common/PageRoleFactory.php
  database/factories/Core/UsersRolesFactory.php
  database/factories/User/Learningtasks/LearningtasksFactory.php
  database/factories/User/Learningtasks/LearningtasksPostsFactory.php
  database/factories/User/Learningtasks/LearningtasksUseSettingsFactory.php
  database/factories/User/Learningtasks/LearningtasksUsersFactory.php
  database/factories/User/Learningtasks/LearningtasksUsersStatusesFactory.php
  resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
  tests/Unit/Plugins/User/Learningtasks/LearningtasksReportCsvExporterTest.php
  tests/Unit/Traits/Learningtasks/LearningtaskPostTraitTest.php
  tests/Unit/Utilities/File/FileUtilsTest.php
Labels: enhancement, plugin(learning-tasks)

#2165 [ページ管理][ユーザ管理] 数万ユーザでもページ開ける, ダウンロードできるように対応
  app/Plugins/Manage/PageManage/PageManage.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Traits/Migration/MigrationTrait.php
  resources/views/plugins/manage/group/edit.blade.php
Labels: enhancement

#2166 [移行ツール] 移行エクスポート＞NC2に移行時間計測追加
  app/Traits/Migration/MigrationTrait.php
Labels: enhancement

#2167 [ユーザ登録][ユーザ管理][プロフィール変更] ログインIDとパスワードの不一致チェック追加
  app/Http/Controllers/Auth/RegisterController.php
  app/Plugins/Manage/UserManage/UserManage.php
  app/Plugins/Mypage/ProfileMypage/ProfileMypage.php
  app/Rules/CustomValiLoginIdAndPasswordDoNotMatch.php
  tests/Browser/Manage/UserManageTest.php
Labels: enhancement

#2169 [移行ツール] 移行エクスポート＞NC3, 移行時間計測追加
  app/Traits/Migration/MigrationLogTrait.php
  app/Traits/Migration/MigrationNc3ExportTrait.php
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#2172 [WYSIWYG] ディレクトリインストールでTinyMCE関連のcssが404になる不具合対応
  public/themes/Defaults/Blue/wysiwyg/content_css.txt
  public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/DarkRed/wysiwyg/content_css.txt
  public/themes/Defaults/DeepPink/wysiwyg/content_css.txt
  public/themes/Defaults/Default/wysiwyg/content_css.txt
  public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt
  public/themes/Defaults/Gray/wysiwyg/content_css.txt
  public/themes/Defaults/Green/wysiwyg/content_css.txt
  public/themes/Defaults/HotPink/wysiwyg/content_css.txt
  public/themes/Defaults/LightGreen/wysiwyg/content_css.txt
  public/themes/Defaults/Lime/wysiwyg/content_css.txt
  public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt
  public/themes/Defaults/Olive/wysiwyg/content_css.txt
  public/themes/Defaults/Orange/wysiwyg/content_css.txt
  public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt
  public/themes/Defaults/Orchid/wysiwyg/content_css.txt
  public/themes/Defaults/Pink/wysiwyg/content_css.txt
  public/themes/Defaults/Purple/wysiwyg/content_css.txt
  public/themes/Defaults/Red/wysiwyg/content_css.txt
  public/themes/Defaults/Teal/wysiwyg/content_css.txt
Labels: bug

#2174 [移行ツール] 移行エクスポート＞NC2, 移行時間計測の出力文字修正
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#2175 [WYSIWYG] ディレクトリインストール＋WYSIWYGでTinyMCE関連のcssが404になる不具合対応2
  public/themes/Defaults/Blue/wysiwyg/content_css.txt
  public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/DarkRed/wysiwyg/content_css.txt
  public/themes/Defaults/DeepPink/wysiwyg/content_css.txt
  public/themes/Defaults/Default/wysiwyg/content_css.txt
  public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt
  public/themes/Defaults/Gray/wysiwyg/content_css.txt
  public/themes/Defaults/Green/wysiwyg/content_css.txt
  public/themes/Defaults/HotPink/wysiwyg/content_css.txt
  public/themes/Defaults/LightGreen/wysiwyg/content_css.txt
  public/themes/Defaults/Lime/wysiwyg/content_css.txt
  public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt
  public/themes/Defaults/Olive/wysiwyg/content_css.txt
  public/themes/Defaults/Orange/wysiwyg/content_css.txt
  public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt
  public/themes/Defaults/Orchid/wysiwyg/content_css.txt
  public/themes/Defaults/Pink/wysiwyg/content_css.txt
  public/themes/Defaults/Purple/wysiwyg/content_css.txt
  public/themes/Defaults/Red/wysiwyg/content_css.txt
  public/themes/Defaults/Teal/wysiwyg/content_css.txt
  resources/views/plugins/common/wysiwyg.blade.php
Labels: bug

#2178 [データベース] 表示設定＞急上昇ワードの下部に説明メッセージ追加
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
Labels: enhancement

#2176 [robots.txt] 他システムから移行後に不要な検索botのクロールを除外
  public/robots.txt
Labels: enhancement

#2179 [開発ツール] sync_option_private_2_dev.shのrsyncのオプション指定見直し
  sync_option_private_2_dev.sh.example
Labels: developer update

#2180 [ページ管理] ページ権限一覧, ページ権限設定で数万ユーザでもページ開けるように対応
  app/Plugins/Manage/PageManage/PageManage.php
  resources/views/plugins/manage/page/role.blade.php
  resources/views/plugins/manage/page/role_list.blade.php
Labels: enhancement

#2181 [robots.txt] 他システムから移行後に不要な検索botのクロールを除外2
  public/robots.txt
Labels: enhancement

#2162 [課題管理]学生がレポート提出内容の修正を行えるようにしました
  app/Enums/LearningtaskUseFunction.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksTool.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_report.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_show_report_status.blade.php
Labels: enhancement, plugin(learning-tasks)

#2182 [フォーム][データベース] 表示順をつまんで移動(ドラック＆ドロップ)できるように対応
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/user/databases/default/databases_edit.blade.php
  resources/views/plugins/user/databases/default/databases_edit_row.blade.php
  resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
  resources/views/plugins/user/forms/default/forms_edit.blade.php
  resources/views/plugins/user/forms/default/forms_edit_row.blade.php
  resources/views/plugins/user/forms/default/forms_edit_row2.blade.php
  resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php
Labels: enhancement

#2173 [JSライブラリ][新着情報][いいね][ブログ][フレーム編集][フォーム][データベース][スライドショー][ページ管理][サイト管理][グループ管理] vue.js 2 → 3にアップデート対応 OW-2521
  package-lock.json
  package.json
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/js/bootstrap.js
  resources/views/core/cms_frame_edit.blade.php
  resources/views/layouts/app.blade.php
  resources/views/plugins/common/like.blade.php
  resources/views/plugins/manage/group/edit.blade.php
  resources/views/plugins/manage/page/page_form.blade.php
  resources/views/plugins/manage/site/site.blade.php
  resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
  resources/views/plugins/user/databases/default/databases_edit_view.blade.php
  resources/views/plugins/user/forms/default/forms_edit_form.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
  resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
  resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
  resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
Labels: developer update
