Repository opensource-workshop/connect-cms, pull requests merged in 2025-08, with the labels that each got.

#2238 [WYSIWYG]カーソル位置を左端にしたときにキャレットが表示されるようにしました
  public/css/app.css
  public/css/connect.css
  public/images/acc_exclamation.png
  public/images/acc_note.png
  public/images/icon_excel.png
  public/images/icon_external.png
  public/images/icon_pdf.png
  public/images/icon_word.png
  public/mix-manifest.json
  resources/images/wysiwyg/acc_exclamation.png
  resources/images/wysiwyg/acc_note.png
  resources/images/wysiwyg/icon_excel.png
  resources/images/wysiwyg/icon_external.png
  resources/images/wysiwyg/icon_pdf.png
  resources/images/wysiwyg/icon_word.png
  resources/sass/app.scss
  resources/sass/wysiwyg/_editor.scss
Labels: enhancement, WYSIWYG

#2241 [アップロードファイル管理] プラン容量表示と使用量警告機能を追加しました
  .env.example
  app/Plugins/Manage/IndexManage/IndexManage.php
  app/Plugins/Manage/UploadfileManage/UploadfileManage.php
  app/Utilities/Storage/StorageUsageCalculator.php
  resources/views/plugins/manage/index/index.blade.php
  resources/views/plugins/manage/uploadfile/index.blade.php
  tests/Unit/Utilities/Storage/StorageUsageCalculatorTest.php
Labels: new feature

#2247 Merge v1.33.1 into 2
  app/Plugins/Manage/SiteManage/SiteManage.php
  app/Traits/Migration/MigrationTrait.php
  app/Traits/Migration/sample/migration_config/migration_config.sample.ini
  config/version.php
  package-lock.json
  resources/views/layouts/app.blade.php
  resources/views/plugins/manage/site/meta.blade.php
  tests/Browser/Manage/SiteManageTest.php
Labels: ignore for release

#2249 [ブログ] 投稿年月での絞り込み機能を追加しました
  app/Enums/BlogNarrowingDownTypeForPostedMonth.php
  app/Models/User/Blogs/Blogs.php
  app/Plugins/User/Blogs/BlogsPlugin.php
  config/app.php
  database/migrations/2025_08_22_135523_add_narrowing_down_type_for_posted_month_to_blogs.php
  resources/views/plugins/user/blogs/default/blogs.blade.php
  resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php
  resources/views/plugins/user/blogs/default/include_narrowing_down_for_posted_month.blade.php
Labels: enhancement

#2252 [アップロードファイル管理] STORAGE_LIMIT_MB未設定時の警告ログを出力しないよう改善しました
  app/Utilities/Storage/StorageUsageCalculator.php
Labels: enhancement
