Repository opensource-workshop/connect-cms, pull requests merged in 2025-06, with the labels that each got.

#2198 [課題管理]レポートのCSV出力処理をリファクタリングしました
  app/Enums/LearningtaskExportType.php
  app/Plugins/User/Learningtasks/Contracts/CsvDataProviderInterface.php
  app/Plugins/User/Learningtasks/Contracts/RowProcessorExceptionHandlerInterface.php
  app/Plugins/User/Learningtasks/Csv/LearningtasksCsvExporter.php
  app/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProvider.php
  app/Plugins/User/Learningtasks/Factories/ColumnDefinitionFactory.php
  app/Plugins/User/Learningtasks/Factories/CsvDataProviderFactory.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksReportCsvExporter.php
  app/Plugins/User/Learningtasks/Providers/LearningtasksServiceProvider.php
  app/Traits/Learningtasks/LearningtaskPostTrait.php
  config/app.php
  resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
  tests/Feature/Plugins/User/Learningtasks/LearningtasksPluginExportCsvTest.php
  tests/Unit/Plugins/User/Learningtasks/Csv/LearningtasksCsvExporterTest.php
  tests/Unit/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProviderTest.php
  tests/Unit/Plugins/User/Learningtasks/Factories/ColumnDefinitionFactoryTest.php
  tests/Unit/Plugins/User/Learningtasks/Factories/CsvDataProviderFactoryTest.php
  tests/Unit/Plugins/User/Learningtasks/Handlers/ReportExceptionHandlerTest.php
  tests/Unit/Plugins/User/Learningtasks/LearningtasksReportCsvExporterTest.php
Labels: ignore for release, developer update

#2206 [課題管理] レポートのコメントに単語数と文字数を表示する機能を追加しました
  app/Enums/LearningtaskUseFunction.php
  app/Models/User/Learningtasks/LearningtasksUsersStatuses.php
  app/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProvider.php
  app/Plugins/User/Learningtasks/Services/LearningtaskReportColumnDefinition.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_edit_report.blade.php
  resources/views/plugins/user/learningtasks/default/learningtasks_show_report_status.blade.php
  tests/Unit/Models/User/Learningtasks/LearningtasksUsersStatusesTest.php
  tests/Unit/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProviderTest.php
Labels: new feature, plugin(learning-tasks)

#2207 [データベース]詳細閲覧時にデータの更新日が更新される不具合を修正しました
  app/Models/User/Databases/DatabasesInputCols.php
  app/Models/User/Databases/DatabasesInputs.php
  app/Observers/User/Databases/DatabasesInputColsObserver.php
  app/Plugins/User/Databases/DatabasesPlugin.php
  app/Providers/EventServiceProvider.php
  database/migrations/2025_01_31_172824_add_last_col_updated_at_to_databases_inputs_table.php
  resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php
  resources/views/plugins/user/databases/default/databases_include_value.blade.php
Labels: bug, plugin(database)

#2210 [開発支援] CLAUDE.mdファイルを追加しました
  CLAUDE.md
Labels: developer update

#2214 #2213 登録データのユーザをダウンロードできるようにしました。
  app/Plugins/User/Forms/FormsPlugin.php
  resources/views/plugins/user/forms/default/forms_list_inputs.blade.php
Labels: new feature
