Repository opensource-workshop/connect-cms, pull requests merged in 2025-03, with the labels that each got.

#2131 [移行インポート＞Groups] 数万件のデータ移行に対応するため、バルクINSERT／upsert対応 他4件
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#2132 [移行インポート＞ユーザ移行] ユーザーのメールアドレスがRFC違反時のエラーメッセージ修正
  app/Traits/Migration/MigrationTrait.php
Labels: developer update

#2129 [WYSIWYG]アイコン表示用クラスの指定方法を修正しました
  public/themes/Defaults/Default/wysiwyg/style_formats.txt
Labels: bug

#2136 [WYSIWYG] WYSIWYGが開けなくなる不具合修正
  public/themes/Defaults/Blue/wysiwyg/content_css.txt
  public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt
  public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt
  public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/DarkRed/wysiwyg/content_css.txt
  public/themes/Defaults/DeepPink/wysiwyg/content_css.txt
  public/themes/Defaults/Default/wysiwyg/content_css.txt
  public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt
  public/themes/Defaults/Gray/wysiwyg/content_css.txt
  public/themes/Defaults/Green/wysiwyg/content_css.txt
  public/themes/Defaults/HotPink/wysiwyg/content_css.txt
  public/themes/Defaults/LightGreen/wysiwyg/content_css.txt
  public/themes/Defaults/Lime/wysiwyg/content_css.txt
  public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt
  public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt
  public/themes/Defaults/Olive/wysiwyg/content_css.txt
  public/themes/Defaults/Orange/wysiwyg/content_css.txt
  public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt
  public/themes/Defaults/Orchid/wysiwyg/content_css.txt
  public/themes/Defaults/Pink/wysiwyg/content_css.txt
  public/themes/Defaults/Purple/wysiwyg/content_css.txt
  public/themes/Defaults/Red/wysiwyg/content_css.txt
  public/themes/Defaults/Teal/wysiwyg/content_css.txt
Labels: bug

#2139 [アイコン] ディレクトリインストール対応 OW-2522
  package-lock.json
  public/css/app.css
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  webpack.mix.js
Labels: bug

#2143 [テスト] DuskテストがChrome 134系になって出るエラーの修正
  tests/Browser/Common/FrameTest.php
  tests/Browser/Common/PasswordPageTest.php
  tests/Browser/Common/WysiwygTest.php
  tests/Browser/ConnectStudy/DroneStudyTest.php
  tests/Browser/Manage/ReservationManageTest.php
  tests/Browser/User/BbsesPluginTest.php
  tests/Browser/User/BlogsPluginTest.php
  tests/Browser/User/CabinetsPluginTest.php
  tests/Browser/User/CalendarsPluginTest.php
  tests/Browser/User/CountersPluginTest.php
  tests/Browser/User/DatabasesPluginTest.php
  tests/Browser/User/DatabasesearchesPluginTest.php
  tests/Browser/User/FaqsPluginTest.php
  tests/Browser/User/FormsPluginTest.php
  tests/Browser/User/LinklistsPluginTest.php
  tests/Browser/User/OpacsPluginTest.php
  tests/Browser/User/OpeningcalendarsPluginTest.php
  tests/Browser/User/PhotoalbumsPluginTest.php
  tests/Browser/User/QuestionnairesPluginTest.php
  tests/Browser/User/ReservationsPluginTest.php
  tests/Browser/User/RssesPluginTest.php
  tests/Browser/User/SearchsPluginTest.php
  tests/Browser/User/SlideshowsPluginTest.php
  tests/Browser/User/TabsPluginTest.php
  tests/Browser/User/ThemechangersPluginTest.php
  tests/Browser/User/WhatsnewsPluginTest.php
  tests/DuskTestCase.php
Labels: developer update

#2137 [アイコン] fortawesome5→6へアップグレード OW-2522
  package-lock.json
  package.json
  public/css/app.css
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff2
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff2
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.eot
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.svg
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.ttf
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff
  public/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2
  public/mix-manifest.json
Labels: enhancement

#2145 [アイコン] fontawesome6にfa-facebook-messengerがないため、fa-commentに修正
  resources/views/plugins/user/databases/default/databases_input.blade.php
  resources/views/plugins/user/forms/default/forms.blade.php
  resources/views/plugins/user/forms/default/index_tandem.blade.php
Labels: enhancement

#2146 [カテゴリ設定] 「文字色」「背景色」の反映に関するメッセージ追記
  resources/views/plugins/common/description_plugin_category.blade.php
  resources/views/plugins/manage/site/categories.blade.php
  resources/views/plugins/manage/site/page_error.blade.php
  resources/views/plugins/manage/user/original_role.blade.php
Labels: enhancement

#2147 [施設管理][ユーザ管理] 管理画面は幅100%表示のため、項目設定のボタン名は常時表示に変更
  resources/views/plugins/manage/reservation/edit_column_detail.blade.php
  resources/views/plugins/manage/reservation/edit_columns.blade.php
  resources/views/plugins/manage/reservation/include_edit_column_row.blade.php
  resources/views/plugins/manage/reservation/include_edit_column_row_add.blade.php
  resources/views/plugins/manage/user/edit_column_detail.blade.php
  resources/views/plugins/manage/user/edit_columns.blade.php
  resources/views/plugins/manage/user/include_edit_column_row.blade.php
  resources/views/plugins/manage/user/include_edit_column_row_add.blade.php
Labels: enhancement

#2150 [Datetimepicker] Tempusdominus-bootstrap-4のcssを5.1.2 → 5.39.2 にアップデート
  package-lock.json
  public/css/app.css
  public/css/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.css
  public/css/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/mix-manifest.json
  resources/sass/app.scss
  resources/sass/tempusdominus-bootstrap-4-build.scss
  resources/views/layouts/app.blade.php
Labels: developer update

#2148 [課題管理]親ページ継承のメンバーシップが正常に機能しない問題を修正しました
  app/Models/Common/Page.php
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksTool.php
  tests/Unit/Models/Common/PageTest.php
Labels: bug, plugin(learning-tasks)

#2149 [課題管理]履歴ファイルへのアクセス権限を適正化しました
  app/Plugins/User/Learningtasks/LearningtasksPlugin.php
  app/Plugins/User/Learningtasks/LearningtasksTool.php
Labels: enhancement, plugin(learning-tasks)

#2153 [View] 使われていない resources/views/ 配下の blade 削除
  app/Http/Controllers/Core/DefaultController.php
  resources/views/404_not_found.blade.php
  resources/views/hello.blade.php
  resources/views/inject_contents.php
  resources/views/manage_call.php
  resources/views/plugin_init.php
  resources/views/test.blade.php
  resources/views/welcome.blade.php
Labels: developer update
